// Generated by the Zebra compiler.
// Source: test/crossmod_arith_test.zbr

const std     = @import("std");
const builtin = @import("builtin");

var _arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
const _allocator = _arena.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _zebra_lt(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.lessThan(u8, a, b);
    return a < b;
}
fn _zebra_le(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) != .gt;
    return a <= b;
}
fn _zebra_gt(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) == .gt;
    return a > b;
}
fn _zebra_ge(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) != .lt;
    return a >= b;
}fn _Result(comptime T: type, comptime E: type) type {
    return union(enum) {
        ok: T,
        err: E,
        pub fn isOk(self: @This()) bool { return self == .ok; }
        pub fn isErr(self: @This()) bool { return self == .err; }
        pub fn unwrap(self: @This()) T {
            return switch (self) { .ok => |v| v, .err => std.debug.panic("unwrap() on error Result\n", .{}) };
        }
        pub fn unwrapOr(self: @This(), default: T) T {
            return switch (self) { .ok => |v| v, .err => default };
        }
        pub fn okValue(self: @This()) ?T {
            return switch (self) { .ok => |v| v, .err => null };
        }
        pub fn errValue(self: @This()) ?E {
            return switch (self) { .ok => null, .err => |e| e };
        }
    };
}
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

fn _zebra_sort_natural(comptime T: type, items: []T) void {
    const _I = struct {
        fn less(_: void, a: T, b: T) bool {
            if (comptime T == []const u8) return std.mem.lessThan(u8, a, b);
            return a < b;
        }
    };
    std.mem.sort(T, items, {}, _I.less);
}
fn _zebra_sort_by(comptime T: type, comptime cmp: anytype, items: []T) void {
    const _I = struct {
        fn less(_: void, a: T, b: T) bool {
            return cmp(a, b);
        }
    };
    std.mem.sort(T, items, {}, _I.less);
}
const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }
const HttpRequest = struct { method: []const u8, path: []const u8, content: []const u8 };
fn _http_serve(port: u16, handler: anytype) void {
    const _alloc = std.heap.page_allocator;
    var _srv = std.net.Address.initIp4(.{ 0, 0, 0, 0 }, port).listen(.{ .reuse_address = true }) catch |e| @panic(@errorName(e));
    defer _srv.deinit();
    while (true) {
        var _conn = _srv.accept() catch continue;
        defer _conn.stream.close();
        // Read request head using recv (works on Windows sockets).
        // We read into a large buffer and scan for \r\n\r\n.
        var _hd: [16384]u8 = undefined;
        var _hl: usize = 0;
        while (_hl < _hd.len - 4096) {
            const _n = std.posix.recv(_conn.stream.handle, _hd[_hl..@min(_hl+4096, _hd.len)], 0) catch break;
            if (_n == 0) break;
            _hl += _n;
            if (std.mem.indexOf(u8, _hd[0.._hl], "\r\n\r\n") != null) break;
        }
        const _hdrs_end = (std.mem.indexOf(u8, _hd[0.._hl], "\r\n\r\n") orelse (_hl -| 4)) + 4;
        const _head = _hd[0.._hdrs_end];
        // Bytes already read after the headers (peeked body).
        var _peeked: usize = if (_hl > _hdrs_end) _hl - _hdrs_end else 0;
        // Parse request line: METHOD PATH VERSION
        const _rl_end = std.mem.indexOf(u8, _head, "\r\n") orelse _hl;
        var _rp = std.mem.splitScalar(u8, _head[0.._rl_end], ' ');
        const _method = _rp.next() orelse "GET";
        const _raw_path = _rp.next() orelse "/";
        const _path = _raw_path[0 .. (std.mem.indexOfScalar(u8, _raw_path, '?') orelse _raw_path.len)];
        // Parse Content-Length for request body.
        var _cl: usize = 0;
        var _hdr_it = std.mem.splitSequence(u8, _head, "\r\n");
        _ = _hdr_it.next();
        while (_hdr_it.next()) |_hl_| {
            if (_hl_.len == 0) break;
            const _cp = std.mem.indexOfScalar(u8, _hl_, ':') orelse continue;
            const _hn = std.mem.trim(u8, _hl_[0.._cp], " ");
            const _hv = std.mem.trim(u8, _hl_[_cp+1..], " ");
            if (std.ascii.eqlIgnoreCase(_hn, "content-length"))
                _cl = std.fmt.parseInt(usize, _hv, 10) catch 0;
        }
        var _body: []const u8 = "";
        if (_cl > 0) {
            const _bb = _alloc.alloc(u8, _cl) catch @panic("OOM");
            // Copy any body bytes already read with the headers.
            const _pre = @min(_peeked, _cl);
            if (_pre > 0) @memcpy(_bb[0.._pre], _hd[_hdrs_end.._hdrs_end+_pre]);
            var _bi: usize = _pre;
            while (_bi < _cl) {
                const _rn = std.posix.recv(_conn.stream.handle, _bb[_bi..], 0) catch break;
                if (_rn == 0) break;
                _bi += _rn;
            }
            _body = _bb[0.._bi];
            _ = &_peeked; // suppress unused warning
        }
        // Invoke handler and write response.
        const _req = HttpRequest{ .method = _method, .path = _path, .content = _body };
        const _resp = if (comptime @typeInfo(@TypeOf(handler)) == .@"fn") handler(_req) else handler.call(_req);
        const _st: []const u8 = switch (_resp.status) {
            200 => "OK", 201 => "Created", 204 => "No Content",
            301 => "Moved Permanently", 302 => "Found",
            400 => "Bad Request", 401 => "Unauthorized", 403 => "Forbidden",
            404 => "Not Found", 405 => "Method Not Allowed",
            500 => "Internal Server Error",
            else => "Unknown",
        };
        const _out = std.fmt.allocPrint(_alloc,
            "HTTP/1.1 {d} {s}\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {d}\r\nConnection: close\r\n\r\n{s}",
            .{ _resp.status, _st, _resp.text.len, _resp.text }) catch @panic("OOM");
        _conn.stream.writeAll(_out) catch {};
    }
}

const TcpConn = struct { stream: std.net.Stream };
fn _tcp_connect(host: []const u8, port: u16) TcpConn {
    const s = std.net.tcpConnectToHost(_allocator, host, port) catch |e| @panic(@errorName(e));
    return .{ .stream = s };
}
fn _tcp_write(conn: TcpConn, data: []const u8) void {
    conn.stream.writeAll(data) catch |e| @panic(@errorName(e));
}
fn _tcp_read(conn: TcpConn) []const u8 {
    var _rb: [65536]u8 = undefined;
    var _rd = conn.stream.reader(&_rb);
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    _ = _rd.interface().streamRemaining(&_hb.writer) catch |e| @panic(@errorName(e));
    return _hb.written();
}
fn _tcp_close(conn: TcpConn) void { conn.stream.close(); }

const UdpSocket = struct { handle: std.posix.socket_t };
fn _udp_socket() UdpSocket {
    const s = std.posix.socket(std.posix.AF.INET, std.posix.SOCK.DGRAM, 0) catch |e| @panic(@errorName(e));
    return .{ .handle = s };
}
fn _udp_send(sock: UdpSocket, host: []const u8, port: u16, data: []const u8) void {
    const dest = std.net.Address.parseIp4(host, port) catch |e| @panic(@errorName(e));
    _ = std.posix.sendto(sock.handle, data, 0, &dest.any, dest.getOsSockLen()) catch |e| @panic(@errorName(e));
}
fn _udp_recv(sock: UdpSocket, max_bytes: usize) []const u8 {
    const buf = std.heap.page_allocator.alloc(u8, max_bytes) catch @panic("OOM");
    const n = std.posix.recv(sock.handle, buf, 0) catch |e| @panic(@errorName(e));
    return buf[0..n];
}
fn _udp_close(sock: UdpSocket) void { std.posix.close(sock.handle); }

fn _net_resolve(host: []const u8) []const []const u8 {
    var _result: std.ArrayList([]const u8) = .{};
    const _list = std.net.getAddressList(std.heap.page_allocator, host, 0) catch return &.{};
    defer _list.deinit();
    for (_list.addrs) |_addr| {
        var _buf: [64]u8 = undefined;
        const _full = std.fmt.bufPrint(&_buf, "{f}", .{_addr}) catch continue;
        const _col = std.mem.lastIndexOfScalar(u8, _full, ':') orelse _full.len;
        var _ip = _full[0.._col];
        if (_ip.len >= 2 and _ip[0] == '[') _ip = _ip[1 .. _ip.len - 1];
        const _owned = std.heap.page_allocator.dupe(u8, _ip) catch continue;
        _result.append(std.heap.page_allocator, _owned) catch {};
    }
    return _result.toOwnedSlice(std.heap.page_allocator) catch &.{};
}
// ─── Thompson NFA regex engine ───────────────────────────────────────────────
const _RNodeKind = enum(u8) { match, lit, dot, cls, split, save };
const _RNode = struct {
    kind: _RNodeKind, c: u8 = 0, bits: [32]u8 = [_]u8{0} ** 32,
    neg: bool = false, slot: u8 = 0, out1: u32 = 0xFFFF_FFFF, out2: u32 = 0xFFFF_FFFF,
};
const _RFrag = struct {
    start: u32, outs: [64]u32 = [_]u32{0xFFFF_FFFF} ** 64, n: u8 = 0,
    fn one(s: u32, d: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d; f.n = 1; return f; }
    fn two(s: u32, d1: u32, d2: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d1; f.outs[1] = d2; f.n = 2; return f; }
    fn merge(a: _RFrag, b: _RFrag) _RFrag {
        var f = _RFrag{ .start = a.start }; var i: u8 = 0;
        for (a.outs[0..a.n]) |o| { f.outs[i] = o; i += 1; }
        for (b.outs[0..b.n]) |o| { f.outs[i] = o; i += 1; }
        f.n = i; return f;
    }
};
const _RC = struct {
    pat: []const u8, pos: usize = 0,
    nodes: std.ArrayListUnmanaged(_RNode) = .{}, alloc: std.mem.Allocator, n_caps: u8 = 0,
    fn addNode(c: *_RC, n: _RNode) error{OutOfMemory}!u32 {
        const idx: u32 = @intCast(c.nodes.items.len);
        try c.nodes.append(c.alloc, n); return idx;
    }
    fn patch(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| c.nodes.items[i & 0x7FFF_FFFF].out1 = t;
    }
    fn patchFrag(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| {
            if (i & 0x8000_0000 != 0) c.nodes.items[i & 0x7FFF_FFFF].out2 = t
            else c.nodes.items[i].out1 = t;
        }
    }
    fn peek(c: *_RC) ?u8 { return if (c.pos < c.pat.len) c.pat[c.pos] else null; }
    fn eat(c: *_RC) ?u8 { if (c.pos < c.pat.len) { defer c.pos += 1; return c.pat[c.pos]; } return null; }
    fn expect(c: *_RC, ch: u8) bool { if (c.peek() == ch) { c.pos += 1; return true; } return false; }
    fn parseClass(c: *_RC) error{OutOfMemory}![32]u8 {
        var bits = [_]u8{0} ** 32;
        while (c.peek()) |ch| {
            if (ch == ']') break; _ = c.eat();
            if (ch == '\\') { const esc = c.eat() orelse break; _rSetEsc(&bits, esc); }
            else if (c.peek() == '-' and c.pos + 1 < c.pat.len and c.pat[c.pos + 1] != ']') {
                _ = c.eat(); const hi = c.eat() orelse ch;
                var i: u8 = ch; while (true) : (i += 1) { _rSetBit(&bits, i); if (i == hi) break; }
            } else _rSetBit(&bits, ch);
        } return bits;
    }
    fn parseAtom(c: *_RC) error{OutOfMemory}!?_RFrag {
        const ch = c.peek() orelse return null;
        switch (ch) {
            '(' => {
                _ = c.eat(); const slot: u8 = c.n_caps * 2; c.n_caps += 1;
                const open = try c.addNode(.{ .kind = .save, .slot = slot });
                if (try c.parseAlt()) |inner| {
                    c.patchFrag(inner, try c.addNode(.{ .kind = .save, .slot = slot + 1 }));
                    _ = c.expect(')');
                    const close: u32 = @intCast(c.nodes.items.len - 1);
                    c.nodes.items[open].out1 = inner.start;
                    return _RFrag.one(open, close);
                }
                _ = c.expect(')'); return _RFrag.one(open, open);
            },
            ')', '|' => return null,
            '[' => {
                _ = c.eat(); const neg = c.expect('^');
                const bits = try c.parseClass(); _ = c.expect(']');
                const idx = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = neg });
                return _RFrag.one(idx, idx);
            },
            '.' => { _ = c.eat(); const _di = try c.addNode(.{ .kind = .dot }); return _RFrag.one(_di, _di); },
            '\\' => {
                _ = c.eat(); const esc = c.eat() orelse return null;
                var bits = [_]u8{0} ** 32;
                const neg = std.ascii.isUpper(esc) and esc != 'B';
                if (neg) { _rSetEsc(&bits, std.ascii.toLower(esc)); const pb = bits; bits = [_]u8{0} ** 32; for (&bits, pb) |*b, p| b.* = ~p; }
                else _rSetEsc(&bits, esc);
                const _ci = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = false });
                return _RFrag.one(_ci, _ci);
            },
            else => { _ = c.eat(); const idx = try c.addNode(.{ .kind = .lit, .c = ch }); return _RFrag.one(idx, idx); },
        }
    }
    fn parsePieceFixed(c: *_RC) error{OutOfMemory}!?_RFrag {
        const atom = try c.parseAtom() orelse return null;
        const q = c.peek() orelse return atom;
        switch (q) {
            '*' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = sp }; f.outs[0] = sp | 0x8000_0000; f.n = 1; return f;
            },
            '+' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = atom.start }; f.outs[0] = sp | 0x8000_0000; f.n = 1; return f;
            },
            '?' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                return _RFrag.two(sp, atom.outs[0], sp | 0x8000_0000);
            },
            else => return atom,
        }
    }
    fn parsePiece(c: *_RC) error{OutOfMemory}!?_RFrag { return c.parsePieceFixed(); }
    fn parseCat(c: *_RC) error{OutOfMemory}!?_RFrag {
        var result: ?_RFrag = try c.parsePiece();
        while (result != null) {
            const next = try c.parsePiece() orelse break;
            c.patchFrag(result.?, next.start);
            result = _RFrag{ .start = result.?.start, .outs = next.outs, .n = next.n };
        }
        return result;
    }
    fn parseAlt(c: *_RC) error{OutOfMemory}!?_RFrag {
        const left = try c.parseCat() orelse return null;
        if (c.peek() != '|') return left;
        _ = c.eat();
        const right = try c.parseAlt() orelse return left;
        const sp = try c.addNode(.{ .kind = .split, .out1 = left.start, .out2 = right.start });
        return _RFrag.merge(_RFrag{ .start = sp, .outs = left.outs, .n = left.n }, right);
    }
};
const Regex = struct {
    nodes: []_RNode, start: u32, alloc: std.mem.Allocator,
    fn closure(re: *const Regex, cur: *std.ArrayListUnmanaged(u32), vis: []bool, alloc: std.mem.Allocator, idx: u32) error{OutOfMemory}!void {
        if (idx == 0xFFFF_FFFF or vis[idx]) return;
        vis[idx] = true;
        switch (re.nodes[idx].kind) {
            .split => { try re.closure(cur, vis, alloc, re.nodes[idx].out1); try re.closure(cur, vis, alloc, re.nodes[idx].out2); },
            .save  => try re.closure(cur, vis, alloc, re.nodes[idx].out1),
            else   => try cur.append(alloc, idx),
        }
    }
    fn matchAt(re: *const Regex, input: []const u8, from: usize) error{OutOfMemory}!?usize {
        const alloc = re.alloc;
        var cur: std.ArrayListUnmanaged(u32) = .{}; var nxt: std.ArrayListUnmanaged(u32) = .{};
        defer cur.deinit(alloc); defer nxt.deinit(alloc);
        const vis = try alloc.alloc(bool, re.nodes.len); defer alloc.free(vis);
        @memset(vis, false); try re.closure(&cur, vis, alloc, re.start);
        var last: ?usize = null;
        for (cur.items) |si| if (re.nodes[si].kind == .match) { last = from; break; };
        var pos = from;
        while (pos < input.len and cur.items.len > 0) : (pos += 1) {
            const ch = input[pos]; nxt.clearRetainingCapacity(); @memset(vis, false);
            for (cur.items) |si| {
                const nd = &re.nodes[si];
                const ok = switch (nd.kind) { .lit => nd.c == ch, .dot => ch != '\n', .cls => _rClsMatch(nd, ch), else => false };
                if (ok) try re.closure(&nxt, vis, alloc, nd.out1);
            }
            std.mem.swap(std.ArrayListUnmanaged(u32), &cur, &nxt);
            for (cur.items) |si| if (re.nodes[si].kind == .match) { last = pos + 1; break; };
        }
        return last;
    }
};
fn _rSetBit(bits: *[32]u8, c: u8) void { bits[c >> 3] |= @as(u8, 1) << @intCast(c & 7); }
fn _rGetBit(bits: *const [32]u8, c: u8) bool { return (bits[c >> 3] >> @intCast(c & 7)) & 1 != 0; }
fn _rClsMatch(nd: *const _RNode, c: u8) bool { const h = _rGetBit(&nd.bits, c); return if (nd.neg) !h else h; }
fn _rSetEsc(bits: *[32]u8, esc: u8) void {
    switch (std.ascii.toLower(esc)) {
        'd' => { var i: u16 = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); },
        'w' => { var i: u16 = 'a'; while (i <= 'z') : (i += 1) _rSetBit(bits, @intCast(i)); i = 'A'; while (i <= 'Z') : (i += 1) _rSetBit(bits, @intCast(i)); i = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); _rSetBit(bits, '_'); },
        's' => { for (" \t\n\r") |c| _rSetBit(bits, c); },
        'n' => _rSetBit(bits, '\n'), 'r' => _rSetBit(bits, '\r'), 't' => _rSetBit(bits, '\t'),
        else => _rSetBit(bits, esc),
    }
}
fn _regex_compile(pattern: []const u8) Regex {
    const alloc = std.heap.page_allocator;
    var c = _RC{ .pat = pattern, .alloc = alloc };
    const frag_opt = c.parseAlt() catch @panic("regex OOM");
    const match_idx = c.addNode(.{ .kind = .match }) catch @panic("regex OOM");
    if (frag_opt) |frag| {
        c.patchFrag(frag, match_idx);
        return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = frag.start, .alloc = alloc };
    }
    return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = match_idx, .alloc = alloc };
}
fn _regex_match(re: Regex, input: []const u8) bool {
    const end = re.matchAt(input, 0) catch return false;
    return end != null and end.? == input.len;
}
fn _regex_find(re: Regex, input: []const u8) []const u8 {
    var i: usize = 0;
    while (i <= input.len) : (i += 1) {
        if (re.matchAt(input, i) catch null) |e| return input[i..e];
    }
    return "";
}
fn _regex_find_all(re: Regex, input: []const u8) []const []const u8 {
    var out: std.ArrayListUnmanaged([]const u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i) catch null) |e| {
            out.append(std.heap.page_allocator, input[i..e]) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else i += 1;
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
fn _regex_replace(re: Regex, input: []const u8, sub: []const u8) []const u8 {
    var out: std.ArrayListUnmanaged(u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i) catch null) |e| {
            out.appendSlice(std.heap.page_allocator, sub) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else {
            out.append(std.heap.page_allocator, input[i]) catch @panic("OOM");
            i += 1;
        }
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
const _MAX_SAVE_SLOTS: usize = 20; // 10 capture groups (open+close slots each)
const _RegThread = struct { state: u32, saves: [_MAX_SAVE_SLOTS]usize };
// Epsilon closure that threads per-state save vectors through the NFA.
// First-wins: if a state is already in cur, later paths are ignored
// (leftmost-greedy semantics).
fn _re_eclosure_s(
    re: *const Regex, cur: *std.ArrayListUnmanaged(_RegThread),
    vis: []bool, alloc: std.mem.Allocator,
    state: u32, saves: [_MAX_SAVE_SLOTS]usize, pos: usize,
) std.mem.Allocator.Error!void {
    if (state == 0xFFFF_FFFF or state >= re.nodes.len) return;
    if (vis[state]) return;
    vis[state] = true;
    const nd = &re.nodes[state];
    switch (nd.kind) {
        .split => {
            try _re_eclosure_s(re, cur, vis, alloc, nd.out1, saves, pos);
            try _re_eclosure_s(re, cur, vis, alloc, nd.out2, saves, pos);
        },
        .save => {
            var ns = saves;
            if (nd.slot < _MAX_SAVE_SLOTS) ns[nd.slot] = pos;
            try _re_eclosure_s(re, cur, vis, alloc, nd.out1, ns, pos);
        },
        else => try cur.append(alloc, .{ .state = state, .saves = saves }),
    }
}
fn _re_match_with_saves(re: *const Regex, input: []const u8, from: usize) ?[_MAX_SAVE_SLOTS]usize {
    const alloc = std.heap.page_allocator;
    const empty: [_MAX_SAVE_SLOTS]usize = [_]usize{0xFFFF_FFFF_FFFF_FFFF} ** _MAX_SAVE_SLOTS;
    var cur: std.ArrayListUnmanaged(_RegThread) = .{};
    defer cur.deinit(alloc);
    var nxt: std.ArrayListUnmanaged(_RegThread) = .{};
    defer nxt.deinit(alloc);
    const vis = alloc.alloc(bool, re.nodes.len) catch return null;
    defer alloc.free(vis);
    @memset(vis, false);
    _re_eclosure_s(re, &cur, vis, alloc, re.start, empty, from) catch return null;
    var last: ?[_MAX_SAVE_SLOTS]usize = null;
    for (cur.items) |t| { if (re.nodes[t.state].kind == .match) { last = t.saves; break; } }
    var pos = from;
    while (pos < input.len and cur.items.len > 0) : (pos += 1) {
        const ch = input[pos]; nxt.clearRetainingCapacity(); @memset(vis, false);
        for (cur.items) |t| {
            const nd = &re.nodes[t.state];
            const ok = switch (nd.kind) { .lit => nd.c == ch, .dot => ch != '\n', .cls => _rClsMatch(nd, ch), else => false };
            if (ok) _re_eclosure_s(re, &nxt, vis, alloc, nd.out1, t.saves, pos + 1) catch {};
        }
        std.mem.swap(std.ArrayListUnmanaged(_RegThread), &cur, &nxt);
        for (cur.items) |t| { if (re.nodes[t.state].kind == .match) { last = t.saves; break; } }
    }
    return last;
}
fn _regex_groups(re: Regex, input: []const u8) []const []const u8 {
    const alloc = std.heap.page_allocator;
    var start: usize = 0;
    while (start <= input.len) : (start += 1) {
        if (_re_match_with_saves(&re, input, start)) |saves| {
            var out: std.ArrayListUnmanaged([]const u8) = .{};
            var i: usize = 0;
            while (i + 1 < _MAX_SAVE_SLOTS) : (i += 2) {
                const s = saves[i]; const e = saves[i + 1];
                if (s == 0xFFFF_FFFF_FFFF_FFFF) break;
                if (e != 0xFFFF_FFFF_FFFF_FFFF and e >= s) out.append(alloc, input[s..e]) catch {};
            }
            return out.toOwnedSlice(alloc) catch &.{};
        }
    }
    return &.{};
}
// ─── GUI: backend isolation ──────────────────────────────────────────────────
// _GuiBackend is an fn-ptr struct.  Swap `_gui_active_backend` to change
// the renderer without touching user code or GuiContext.
const _GuiBackend = struct {
    initFn:        *const fn (title: []const u8, width: i64, height: i64) anyerror!void,
    deinitFn:      *const fn () void,
    newFrameFn:    *const fn () bool,
    endFrameFn:    *const fn () void,
    textFn:        *const fn (s: []const u8) void,
    separatorFn:   *const fn () void,
    sameLineFn:    *const fn () void,
    spacingFn:     *const fn () void,
    indentFn:      *const fn () void,
    unindentFn:    *const fn () void,
    buttonFn:      *const fn (label: []const u8) bool,
    checkboxFn:    *const fn (label: []const u8, value: bool) bool,
    sliderFn:      *const fn (label: []const u8, value: f64, min: f64, max: f64) f64,
    inputFn:       *const fn (label: []const u8, value: []const u8) []const u8,
    inputMultilineFn: *const fn (label: []const u8, value: []const u8, width: f64, height: f64) []const u8,
    beginPanelFn:  *const fn (label: []const u8) bool,
    endPanelFn:    *const fn () void,
    beginWindowFn: *const fn (label: []const u8) bool,
    endWindowFn:   *const fn () void,
};
const GuiContext = struct {
    _b: *const _GuiBackend,
    pub fn text(self: GuiContext, s: []const u8) void { self._b.textFn(s); }
    pub fn separator(self: GuiContext) void { self._b.separatorFn(); }
    pub fn sameLine(self: GuiContext) void { self._b.sameLineFn(); }
    pub fn spacing(self: GuiContext) void { self._b.spacingFn(); }
    pub fn indent(self: GuiContext) void { self._b.indentFn(); }
    pub fn unindent(self: GuiContext) void { self._b.unindentFn(); }
    pub fn button(self: GuiContext, label: []const u8) bool { return self._b.buttonFn(label); }
    pub fn checkbox(self: GuiContext, label: []const u8, value: bool) bool { return self._b.checkboxFn(label, value); }
    pub fn slider(self: GuiContext, label: []const u8, value: f64, min: f64, max: f64) f64 { return self._b.sliderFn(label, value, min, max); }
    pub fn input(self: GuiContext, label: []const u8, value: []const u8) []const u8 { return self._b.inputFn(label, value); }
    pub fn inputMultiline(self: GuiContext, label: []const u8, value: []const u8, width: f64, height: f64) []const u8 { return self._b.inputMultilineFn(label, value, width, height); }
    pub fn panel(self: GuiContext, label: []const u8, callback: anytype) void {
        if (self._b.beginPanelFn(label)) {
            if (comptime @typeInfo(@TypeOf(callback)) == .@"fn") callback(self) else callback.call(self);
            self._b.endPanelFn();
        }
    }
    pub fn window(self: GuiContext, label: []const u8, callback: anytype) void {
        if (self._b.beginWindowFn(label)) {
            if (comptime @typeInfo(@TypeOf(callback)) == .@"fn") callback(self) else callback.call(self);
            self._b.endWindowFn();
        }
    }
};
fn _gui_run(title: []const u8, width: i64, height: i64, frame: anytype) void {
    _gui_active_backend.initFn(title, width, height) catch @panic("gui init failed");
    defer _gui_active_backend.deinitFn();
    const _g = GuiContext{ ._b = &_gui_active_backend };
    if (comptime @typeInfo(@TypeOf(frame)) == .@"fn") {
        while (_gui_active_backend.newFrameFn()) {
            frame(_g);
            _gui_active_backend.endFrameFn();
        }
    } else {
        var _mframe = frame;
        while (_gui_active_backend.newFrameFn()) {
            _mframe.call(_g);
            _gui_active_backend.endFrameFn();
        }
    }
}
// ─── Stub backend (single frame, prints to stderr) ───────────────────────────
fn _stub_init(title: []const u8, width: i64, height: i64) anyerror!void {
    _ = title; _ = width; _ = height;
}
fn _stub_deinit() void {}
var _stub_frame_count: u8 = 0;
fn _stub_new_frame() bool {
    if (_stub_frame_count >= 1) return false;
    _stub_frame_count += 1;
    return true;
}
fn _stub_end_frame() void {}
fn _stub_text(s: []const u8) void { std.debug.print("[gui] text: {s}\n", .{s}); }
fn _stub_separator() void { std.debug.print("[gui] ---\n", .{}); }
fn _stub_same_line() void { std.debug.print("[gui] sameLine\n", .{}); }
fn _stub_spacing() void { std.debug.print("[gui] spacing\n", .{}); }
fn _stub_indent() void { std.debug.print("[gui] indent\n", .{}); }
fn _stub_unindent() void { std.debug.print("[gui] unindent\n", .{}); }
fn _stub_button(label: []const u8) bool {
    std.debug.print("[gui] button: {s}\n", .{label});
    return false;
}
fn _stub_checkbox(label: []const u8, value: bool) bool {
    std.debug.print("[gui] checkbox: {s} = {}\n", .{ label, value });
    return value;
}
fn _stub_slider(label: []const u8, value: f64, min: f64, max: f64) f64 {
    std.debug.print("[gui] slider: {s} = {d} [{d}, {d}]\n", .{ label, value, min, max });
    return value;
}
fn _stub_input(label: []const u8, value: []const u8) []const u8 {
    std.debug.print("[gui] input: {s} = {s}\n", .{ label, value });
    return value;
}
fn _stub_input_multiline(label: []const u8, value: []const u8, width: f64, height: f64) []const u8 {
    std.debug.print("[gui] inputMultiline: {s} ({d}x{d})\n", .{ label, width, height });
    return value;
}
fn _stub_begin_panel(label: []const u8) bool {
    std.debug.print("[gui] panel: {s}\n", .{label});
    return true;
}
fn _stub_end_panel() void {}
fn _stub_begin_window(label: []const u8) bool {
    std.debug.print("[gui] window: {s}\n", .{label});
    return true;
}
fn _stub_end_window() void {}
const _gui_stub_backend = _GuiBackend{
    .initFn        = _stub_init,
    .deinitFn      = _stub_deinit,
    .newFrameFn    = _stub_new_frame,
    .endFrameFn    = _stub_end_frame,
    .textFn        = _stub_text,
    .separatorFn   = _stub_separator,
    .sameLineFn    = _stub_same_line,
    .spacingFn     = _stub_spacing,
    .indentFn      = _stub_indent,
    .unindentFn    = _stub_unindent,
    .buttonFn      = _stub_button,
    .checkboxFn    = _stub_checkbox,
    .sliderFn      = _stub_slider,
    .inputFn       = _stub_input,
    .inputMultilineFn = _stub_input_multiline,
    .beginPanelFn  = _stub_begin_panel,
    .endPanelFn    = _stub_end_panel,
    .beginWindowFn = _stub_begin_window,
    .endWindowFn   = _stub_end_window,
};
const _gui_active_backend: _GuiBackend = _gui_stub_backend;
const MathUtils = @import("MathUtils.zig").MathUtils;
pub const App = struct {
    pub fn testBasicArithmetic() void {
        const d = MathUtils.double(5);
        const s = MathUtils.square(3);
        const sum = (d + s);
        std.debug.print("{}\n", .{sum});
    }

    pub fn testMathCombos() void {
        const x = MathUtils.double(10);
        const y = MathUtils.cube(2);
        const z = MathUtils.max(x, y);
        std.debug.print("{}\n", .{z});
    }

    pub fn testChaining() void {
        const result = MathUtils.square(MathUtils.double(3));
        std.debug.print("{}\n", .{result});
    }

    pub fn main() void {
        App.testBasicArithmetic();
        App.testMathCombos();
        App.testChaining();
    }

};

pub fn main() !void {
    defer _arena.deinit();
    App.main();
}
