// Generated by the Zebra compiler.
// Source: test/hashmap_iter.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

pub const Program = struct {
    pub fn main() void {
        var scores = std.StringHashMap(i64).init(_allocator);
        defer scores.deinit();
        scores.put("alice", 10) catch unreachable;
        scores.put("bob", 20) catch unreachable;
        var total: i64 = 0;
        var _it_k = scores.iterator();
        while (_it_k.next()) |_e_k| {
            const k = _e_k.key_ptr.*;
            _ = k;
            const v = _e_k.value_ptr.*;
            total = (total + v);
        }
        std.debug.print("{}\n", .{total});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Program.main();
}
