// Generated by the Zebra compiler.
// Source: test/interface_test.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

pub fn Greetable(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "greet")) @compileError("type " ++ @typeName(T) ++ " does not implement Greetable.greet");
        if (!@hasDecl(T, "greetName")) @compileError("type " ++ @typeName(T) ++ " does not implement Greetable.greetName");
    }
}

pub const English = struct {
    pub fn greet(self: *English) []const u8 {
        _ = self;
        return "Hello";
    }

    pub fn greetName(self: *English, name: []const u8) []const u8 {
        _ = self;
        return (std.mem.concat(_allocator, u8, &.{ "Hello, ", name }) catch unreachable);
    }


    comptime {
        Greetable(@This());
    }
};

pub const Spanish = struct {
    pub fn greet(self: *Spanish) []const u8 {
        _ = self;
        return "Hola";
    }

    pub fn greetName(self: *Spanish, name: []const u8) []const u8 {
        _ = self;
        return (std.mem.concat(_allocator, u8, &.{ "Hola, ", name }) catch unreachable);
    }


    comptime {
        Greetable(@This());
    }
};

pub const Counter = struct {
    count: i64 = undefined,
    pub fn init() Counter {
        var self: Counter = undefined;
        self.count = 0;
        return self;
    }

    pub fn increment(self: *Counter) void {
        self.count = (self.count + 1);
    }

    pub fn value(self: *Counter) i64 {
        return self.count;
    }

};

pub const Main = struct {
    pub fn main() void {
        var e = English{};
        var s = Spanish{};
        std.debug.print("{s}\n", .{e.greet()});
        std.debug.print("{s}\n", .{s.greet()});
        std.debug.print("{s}\n", .{e.greetName("Alice")});
        std.debug.print("{s}\n", .{s.greetName("Bob")});
        var c = Counter.init();
        c.increment();
        c.increment();
        c.increment();
        std.debug.print("{}\n", .{c.value()});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Main.main();
}
