// Auto-generated by the Zebra compiler.  DO NOT EDIT.
// Source: test/mathlib_test.zbr
#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// MathLib
int64_t MathLib_add(int64_t a, int64_t b);
int64_t MathLib_mul(int64_t a, int64_t b);
double MathLib_clamp(double val, double lo, double hi);
bool MathLib_isEven(int64_t n);

