// Generated by the Zebra compiler.
// Source: test/raise_auto.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?*anyopaque = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};

pub const App = struct {
    pub fn risky(x: i64) anyerror!i64 {
        if ((x < 0)) {
            _error_ctx = .{ .message = "negative value", .details = @as(*anyopaque, @ptrCast(@constCast(@alignCast(&(x)))))  };
            return error.ZebraError;
        }
        return (x * 2);
    }

    pub fn main() void {
        var result: i64 = 0;
        var _try_err_29a8: ?anyerror = null;
        _try_blk_29a8: {
            result = App.risky(5) catch |_tc_2a373a72938| { _try_err_29a8 = _tc_2a373a72938; break :_try_blk_29a8; };
            break :_try_blk_29a8;
        }
        if (_try_err_29a8 != null) {
            result = (-1);
        }
        std.debug.print("{}\n", .{result});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    App.main();
}
