// Generated by the Zebra compiler.
// Source: test/raise_details_test.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

pub const FileInfo = struct {
    path: []const u8 = undefined,
    code: i64 = undefined,
    pub fn init(p: []const u8, c: i64) FileInfo {
        var self: FileInfo = undefined;
        self.path = p;
        self.code = c;
        return self;
    }

    pub fn toString(self: *FileInfo) []const u8 {
        return (std.mem.concat(_allocator, u8, &.{ (std.mem.concat(_allocator, u8, &.{ "FileInfo(", self.path }) catch unreachable), ")" }) catch unreachable);
    }

};

pub const Main = struct {
    pub fn tryRead(path: []const u8) anyerror!void {
        { const _rdet_530 = _allocator.create(FileInfo) catch @panic("OOM");
          _rdet_530.* = FileInfo.init(path, 404);
          const _rshim_530 = struct { fn call(p: *anyopaque) []const u8 {
              return @as(*FileInfo, @alignCast(@ptrCast(p))).toString();
          } };
          _error_ctx = .{ .message = "file not found", .details = .{ .ptr = @ptrCast(_rdet_530), .toString_fn = _rshim_530.call } };
        }
        return error.ZebraError;
    }

    pub fn main() void {
        var _try_err_52b8: ?anyerror = null;
        _try_blk_52b8: {
            Main.tryRead("data.txt") catch |_e| { _try_err_52b8 = _e; break :_try_blk_52b8; };
            break :_try_blk_52b8;
        }
        if (_try_err_52b8 != null) {
            std.debug.print("{s}\n", .{_error_ctx.message});
            {
                const _pt0 = (if (_error_ctx.details) |_det| _det.toString() else "");
                defer _allocator.free(_pt0);
                std.debug.print("{s}\n", .{_pt0});
            }
        }
        var _try_err_54e0: ?anyerror = null;
        _try_blk_54e0: {
            _error_ctx = .{ .message = "simple error", .details = null };
            _try_err_54e0 = error.ZebraError;
            break :_try_blk_54e0;
        }
        if (_try_err_54e0 != null) {
            std.debug.print("{s}\n", .{_error_ctx.message});
        }
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Main.main();
}
