// Generated by the Zebra compiler.
// Source: test/regex_test.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

const TcpConn = struct { stream: std.net.Stream };
fn _tcp_connect(host: []const u8, port: u16) TcpConn {
    const s = std.net.tcpConnectToHost(_allocator, host, port) catch |e| @panic(@errorName(e));
    return .{ .stream = s };
}
fn _tcp_write(conn: TcpConn, data: []const u8) void {
    conn.stream.writeAll(data) catch |e| @panic(@errorName(e));
}
fn _tcp_read(conn: TcpConn) []const u8 {
    var _rb: [65536]u8 = undefined;
    var _rd = conn.stream.reader(&_rb);
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    _ = _rd.interface().streamRemaining(&_hb.writer) catch |e| @panic(@errorName(e));
    return _hb.written();
}
fn _tcp_close(conn: TcpConn) void { conn.stream.close(); }

const UdpSocket = struct { handle: std.posix.socket_t };
fn _udp_socket() UdpSocket {
    const s = std.posix.socket(std.posix.AF.INET, std.posix.SOCK.DGRAM, 0) catch |e| @panic(@errorName(e));
    return .{ .handle = s };
}
fn _udp_send(sock: UdpSocket, host: []const u8, port: u16, data: []const u8) void {
    const dest = std.net.Address.parseIp4(host, port) catch |e| @panic(@errorName(e));
    _ = std.posix.sendto(sock.handle, data, 0, &dest.any, dest.getOsSockLen()) catch |e| @panic(@errorName(e));
}
fn _udp_recv(sock: UdpSocket, max_bytes: usize) []const u8 {
    const buf = std.heap.page_allocator.alloc(u8, max_bytes) catch @panic("OOM");
    const n = std.posix.recv(sock.handle, buf, 0) catch |e| @panic(@errorName(e));
    return buf[0..n];
}
fn _udp_close(sock: UdpSocket) void { std.posix.close(sock.handle); }

// ─── Thompson NFA regex engine ───────────────────────────────────────────────
const _RNodeKind = enum(u8) { match, lit, dot, cls, split, save };
const _RNode = struct {
    kind: _RNodeKind, c: u8 = 0, bits: [32]u8 = [_]u8{0} ** 32,
    neg: bool = false, slot: u8 = 0, out1: u32 = 0xFFFF_FFFF, out2: u32 = 0xFFFF_FFFF,
};
const _RFrag = struct {
    start: u32, outs: [64]u32 = [_]u32{0xFFFF_FFFF} ** 64, n: u8 = 0,
    fn one(s: u32, d: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d; f.n = 1; return f; }
    fn two(s: u32, d1: u32, d2: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d1; f.outs[1] = d2; f.n = 2; return f; }
    fn merge(a: _RFrag, b: _RFrag) _RFrag {
        var f = _RFrag{ .start = a.start }; var i: u8 = 0;
        for (a.outs[0..a.n]) |o| { f.outs[i] = o; i += 1; }
        for (b.outs[0..b.n]) |o| { f.outs[i] = o; i += 1; }
        f.n = i; return f;
    }
};
const _RC = struct {
    pat: []const u8, pos: usize = 0,
    nodes: std.ArrayListUnmanaged(_RNode) = .{}, alloc: std.mem.Allocator, n_caps: u8 = 0,
    fn addNode(c: *_RC, n: _RNode) error{OutOfMemory}!u32 {
        const idx: u32 = @intCast(c.nodes.items.len);
        try c.nodes.append(c.alloc, n); return idx;
    }
    fn patch(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| c.nodes.items[i & 0x7FFF_FFFF].out1 = t;
    }
    fn patchFrag(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| {
            if (i & 0x8000_0000 != 0) c.nodes.items[i & 0x7FFF_FFFF].out2 = t
            else c.nodes.items[i].out1 = t;
        }
    }
    fn peek(c: *_RC) ?u8 { return if (c.pos < c.pat.len) c.pat[c.pos] else null; }
    fn eat(c: *_RC) ?u8 { if (c.pos < c.pat.len) { defer c.pos += 1; return c.pat[c.pos]; } return null; }
    fn expect(c: *_RC, ch: u8) bool { if (c.peek() == ch) { c.pos += 1; return true; } return false; }
    fn parseClass(c: *_RC) error{OutOfMemory}![32]u8 {
        var bits = [_]u8{0} ** 32;
        while (c.peek()) |ch| {
            if (ch == ']') break; _ = c.eat();
            if (ch == '\\') { const esc = c.eat() orelse break; _rSetEsc(&bits, esc); }
            else if (c.peek() == '-' and c.pos + 1 < c.pat.len and c.pat[c.pos + 1] != ']') {
                _ = c.eat(); const hi = c.eat() orelse ch;
                var i: u8 = ch; while (true) : (i += 1) { _rSetBit(&bits, i); if (i == hi) break; }
            } else _rSetBit(&bits, ch);
        } return bits;
    }
    fn parseAtom(c: *_RC) error{OutOfMemory}!?_RFrag {
        const ch = c.peek() orelse return null;
        switch (ch) {
            '(' => {
                _ = c.eat(); const slot: u8 = c.n_caps * 2; c.n_caps += 1;
                const open = try c.addNode(.{ .kind = .save, .slot = slot });
                if (try c.parseAlt()) |inner| {
                    c.patch(inner, try c.addNode(.{ .kind = .save, .slot = slot + 1 }));
                    _ = c.expect(')');
                    const close: u32 = @intCast(c.nodes.items.len - 1);
                    c.nodes.items[open].out1 = inner.start;
                    return _RFrag.one(open, close);
                }
                _ = c.expect(')'); return _RFrag.one(open, open);
            },
            ')', '|' => return null,
            '[' => {
                _ = c.eat(); const neg = c.expect('^');
                const bits = try c.parseClass(); _ = c.expect(']');
                const idx = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = neg });
                return _RFrag.one(idx, idx);
            },
            '.' => { _ = c.eat(); const _di = try c.addNode(.{ .kind = .dot }); return _RFrag.one(_di, _di); },
            '\\' => {
                _ = c.eat(); const esc = c.eat() orelse return null;
                var bits = [_]u8{0} ** 32;
                const neg = std.ascii.isUpper(esc) and esc != 'B';
                if (neg) { _rSetEsc(&bits, std.ascii.toLower(esc)); const pb = bits; bits = [_]u8{0} ** 32; for (&bits, pb) |*b, p| b.* = ~p; }
                else _rSetEsc(&bits, esc);
                const _ci = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = false });
                return _RFrag.one(_ci, _ci);
            },
            else => { _ = c.eat(); const idx = try c.addNode(.{ .kind = .lit, .c = ch }); return _RFrag.one(idx, idx); },
        }
    }
    fn parsePieceFixed(c: *_RC) error{OutOfMemory}!?_RFrag {
        const atom = try c.parseAtom() orelse return null;
        const q = c.peek() orelse return atom;
        switch (q) {
            '*' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = sp }; f.outs[0] = sp | 0x8000_0000; f.n = 1; return f;
            },
            '+' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = atom.start }; f.outs[0] = sp | 0x8000_0000; f.n = 1; return f;
            },
            '?' => {
                _ = c.eat();
                const sp = try c.addNode(.{ .kind = .split, .out1 = atom.start, .out2 = 0xFFFF_FFFF });
                return _RFrag.two(sp, atom.outs[0], sp | 0x8000_0000);
            },
            else => return atom,
        }
    }
    fn parsePiece(c: *_RC) error{OutOfMemory}!?_RFrag { return c.parsePieceFixed(); }
    fn parseCat(c: *_RC) error{OutOfMemory}!?_RFrag {
        var result: ?_RFrag = try c.parsePiece();
        while (result != null) {
            const next = try c.parsePiece() orelse break;
            c.patchFrag(result.?, next.start);
            result = _RFrag{ .start = result.?.start, .outs = next.outs, .n = next.n };
        }
        return result;
    }
    fn parseAlt(c: *_RC) error{OutOfMemory}!?_RFrag {
        const left = try c.parseCat() orelse return null;
        if (c.peek() != '|') return left;
        _ = c.eat();
        const right = try c.parseAlt() orelse return left;
        const sp = try c.addNode(.{ .kind = .split, .out1 = left.start, .out2 = right.start });
        return _RFrag.merge(_RFrag{ .start = sp, .outs = left.outs, .n = left.n }, right);
    }
};
const Regex = struct {
    nodes: []_RNode, start: u32, alloc: std.mem.Allocator,
    fn closure(re: *const Regex, cur: *std.ArrayListUnmanaged(u32), vis: []bool, alloc: std.mem.Allocator, idx: u32) error{OutOfMemory}!void {
        if (idx == 0xFFFF_FFFF or vis[idx]) return;
        vis[idx] = true;
        switch (re.nodes[idx].kind) {
            .split => { try re.closure(cur, vis, alloc, re.nodes[idx].out1); try re.closure(cur, vis, alloc, re.nodes[idx].out2); },
            .save  => try re.closure(cur, vis, alloc, re.nodes[idx].out1),
            else   => try cur.append(alloc, idx),
        }
    }
    fn matchAt(re: *const Regex, input: []const u8, from: usize) error{OutOfMemory}!?usize {
        const alloc = re.alloc;
        var cur: std.ArrayListUnmanaged(u32) = .{}; var nxt: std.ArrayListUnmanaged(u32) = .{};
        defer cur.deinit(alloc); defer nxt.deinit(alloc);
        const vis = try alloc.alloc(bool, re.nodes.len); defer alloc.free(vis);
        @memset(vis, false); try re.closure(&cur, vis, alloc, re.start);
        var last: ?usize = null;
        for (cur.items) |si| if (re.nodes[si].kind == .match) { last = from; break; };
        var pos = from;
        while (pos < input.len and cur.items.len > 0) : (pos += 1) {
            const ch = input[pos]; nxt.clearRetainingCapacity(); @memset(vis, false);
            for (cur.items) |si| {
                const nd = &re.nodes[si];
                const ok = switch (nd.kind) { .lit => nd.c == ch, .dot => ch != '\n', .cls => _rClsMatch(nd, ch), else => false };
                if (ok) try re.closure(&nxt, vis, alloc, nd.out1);
            }
            std.mem.swap(std.ArrayListUnmanaged(u32), &cur, &nxt);
            for (cur.items) |si| if (re.nodes[si].kind == .match) { last = pos + 1; break; };
        }
        return last;
    }
};
fn _rSetBit(bits: *[32]u8, c: u8) void { bits[c >> 3] |= @as(u8, 1) << @intCast(c & 7); }
fn _rGetBit(bits: *const [32]u8, c: u8) bool { return (bits[c >> 3] >> @intCast(c & 7)) & 1 != 0; }
fn _rClsMatch(nd: *const _RNode, c: u8) bool { const h = _rGetBit(&nd.bits, c); return if (nd.neg) !h else h; }
fn _rSetEsc(bits: *[32]u8, esc: u8) void {
    switch (std.ascii.toLower(esc)) {
        'd' => { var i: u16 = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); },
        'w' => { var i: u16 = 'a'; while (i <= 'z') : (i += 1) _rSetBit(bits, @intCast(i)); i = 'A'; while (i <= 'Z') : (i += 1) _rSetBit(bits, @intCast(i)); i = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); _rSetBit(bits, '_'); },
        's' => { for (" \t\n\r") |c| _rSetBit(bits, c); },
        'n' => _rSetBit(bits, '\n'), 'r' => _rSetBit(bits, '\r'), 't' => _rSetBit(bits, '\t'),
        else => _rSetBit(bits, esc),
    }
}
fn _regex_compile(pattern: []const u8) Regex {
    const alloc = std.heap.page_allocator;
    var c = _RC{ .pat = pattern, .alloc = alloc };
    const frag_opt = c.parseAlt() catch @panic("regex OOM");
    const match_idx = c.addNode(.{ .kind = .match }) catch @panic("regex OOM");
    if (frag_opt) |frag| {
        c.patchFrag(frag, match_idx);
        return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = frag.start, .alloc = alloc };
    }
    return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = match_idx, .alloc = alloc };
}
fn _regex_match(re: Regex, input: []const u8) bool {
    const end = re.matchAt(input, 0) catch return false;
    return end != null and end.? == input.len;
}
fn _regex_find(re: Regex, input: []const u8) []const u8 {
    var i: usize = 0;
    while (i <= input.len) : (i += 1) {
        if (re.matchAt(input, i) catch null) |e| return input[i..e];
    }
    return "";
}
fn _regex_find_all(re: Regex, input: []const u8) []const []const u8 {
    var out: std.ArrayListUnmanaged([]const u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i) catch null) |e| {
            out.append(std.heap.page_allocator, input[i..e]) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else i += 1;
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
fn _regex_replace(re: Regex, input: []const u8, sub: []const u8) []const u8 {
    var out: std.ArrayListUnmanaged(u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i) catch null) |e| {
            out.appendSlice(std.heap.page_allocator, sub) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else {
            out.append(std.heap.page_allocator, input[i]) catch @panic("OOM");
            i += 1;
        }
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
pub const Main = struct {
    pub fn main() void {
        const re1: Regex = _regex_compile("hello");
        std.debug.print("{}\n", .{_regex_match(re1, "hello")});
        std.debug.print("{}\n", .{_regex_match(re1, "world")});
        const re2: Regex = _regex_compile("h.*o");
        std.debug.print("{}\n", .{_regex_match(re2, "hello")});
        std.debug.print("{}\n", .{_regex_match(re2, "ho")});
        std.debug.print("{}\n", .{_regex_match(re2, "hi")});
        const re3: Regex = _regex_compile("\\d+");
        std.debug.print("{}\n", .{_regex_match(re3, "42")});
        std.debug.print("{}\n", .{_regex_match(re3, "abc")});
        const re4: Regex = _regex_compile("cat|dog");
        std.debug.print("{}\n", .{_regex_match(re4, "cat")});
        std.debug.print("{}\n", .{_regex_match(re4, "dog")});
        std.debug.print("{}\n", .{_regex_match(re4, "fish")});
        const re5: Regex = _regex_compile("\\d+");
        std.debug.print("{s}\n", .{_regex_find(re5, "abc 42 def")});
        std.debug.print("{s}\n", .{_regex_find(re5, "no digits")});
        const re6: Regex = _regex_compile("\\d+\\.\\d+");
        std.debug.print("{}\n", .{_regex_match(re6, "3.14")});
        std.debug.print("{}\n", .{_regex_match(re6, "3")});
        const re7: Regex = _regex_compile("\\d+");
        for (_regex_find_all(re7, "one 1 two 22 three 333")) |m| {
            std.debug.print("{s}\n", .{m});
        }
        const re8: Regex = _regex_compile("\\d+");
        std.debug.print("{s}\n", .{_regex_replace(re8, "abc 42 def 99", "NUM")});
        std.debug.print("{s}\n", .{_regex_replace(re8, "no digits here", "X")});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Main.main();
}
