// Generated by the Zebra compiler.
// Source: test/selfhost_probe5.zbr

const std     = @import("std");
const builtin = @import("builtin");

var _arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var _allocator: std.mem.Allocator = undefined;
pub fn _initAllocator(a: std.mem.Allocator) void {
    _allocator = a;
}

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _zebra_lt(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.lessThan(u8, a, b);
    return a < b;
}
fn _zebra_le(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) != .gt;
    return a <= b;
}
fn _zebra_gt(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) == .gt;
    return a > b;
}
fn _zebra_ge(a: anytype, b: anytype) bool {
    if (comptime @TypeOf(a) == []const u8) return std.mem.order(u8, a, b) != .lt;
    return a >= b;
}
/// `item in container` — membership test for List, string (substring), HashMap.
fn _zebra_in(item: anytype, container: anytype) bool {
    const C = @TypeOf(container);
    const I = @TypeOf(item);
    // Struct types: ArrayList (has .items field) or HashMap (has .contains decl).
    if (comptime @typeInfo(C) == .@"struct") {
        if (comptime @hasField(C, "items")) {
            for (container.items) |elem| {
                if (comptime I == []const u8 or @typeInfo(I) == .pointer) {
                    if (std.mem.eql(u8, elem, item)) return true;
                } else {
                    if (elem == item) return true;
                }
            }
            return false;
        }
        if (comptime @hasDecl(C, "contains")) return container.contains(item);
        return false;
    }
    // Pointer/array types: string substring check (coerce to []const u8).
    return std.mem.indexOf(u8, @as([]const u8, container), @as([]const u8, item)) != null;
}
/// `s + t` — string concatenation.
fn _str_concat(a: []const u8, b: []const u8, alloc: std.mem.Allocator) []const u8 {
    return std.mem.concat(alloc, u8, &.{ a, b }) catch @panic("OOM");
}
/// `s * n` — repeat string s n times.
fn _str_repeat(s: []const u8, n: anytype, alloc: std.mem.Allocator) []const u8 {
    const count: usize = @intCast(n);
    if (count == 0 or s.len == 0) return "";
    const buf = alloc.alloc(u8, s.len * count) catch @panic("OOM");
    for (0..count) |i| @memcpy(buf[i * s.len ..][0..s.len], s);
    return buf;
}
/// FNV-1a 32-bit hash — used as the type-arg component of _type_tag.
/// Low 32 bits of _ttag_ClassName hold the class hash; high 32 bits
/// hold the combined type-arg hash for generic instantiations (Phase 3).
/// Also usable as Symbol.hash for fast string identity comparison.
fn _zbr_hash(comptime s: []const u8) u32 {
    comptime var h: u32 = 2166136261;
    comptime for (s) |c| { h ^= c; h *%= 16777619; };
    return h;
}fn _Result(comptime T: type, comptime E: type) type {
    return union(enum) {
        ok: T,
        err: E,
        pub fn isOk(self: @This()) bool { return self == .ok; }
        pub fn isErr(self: @This()) bool { return self == .err; }
        pub fn unwrap(self: @This()) T {
            return switch (self) { .ok => |v| v, .err => std.debug.panic("unwrap() on error Result\n", .{}) };
        }
        pub fn unwrapOr(self: @This(), default: T) T {
            return switch (self) { .ok => |v| v, .err => default };
        }
        pub fn okValue(self: @This()) ?T {
            return switch (self) { .ok => |v| v, .err => null };
        }
        pub fn errValue(self: @This()) ?E {
            return switch (self) { .ok => null, .err => |e| e };
        }
        /// map(f) — apply f to the ok value; propagate err unchanged.
        /// f may be a fn pointer or a capture-closure struct with a `call` method.
        pub fn map(self: @This(), f: anytype) _Result(
            @TypeOf(if (comptime @typeInfo(@TypeOf(f)) == .@"fn") f(@as(T, undefined)) else f.call(@as(T, undefined))), E
        ) {
            const _is_fn = comptime @typeInfo(@TypeOf(f)) == .@"fn";
            return switch (self) {
                .ok  => |v| .{ .ok = if (_is_fn) f(v) else f.call(v) },
                .err => |e| .{ .err = e },
            };
        }
        /// flatMap(f) — apply f to the ok value; f must return Result(U, E).
        pub fn flatMap(self: @This(), f: anytype) @TypeOf(
            if (comptime @typeInfo(@TypeOf(f)) == .@"fn") f(@as(T, undefined)) else f.call(@as(T, undefined))
        ) {
            const _is_fn = comptime @typeInfo(@TypeOf(f)) == .@"fn";
            return switch (self) {
                .ok  => |v| if (_is_fn) f(v) else f.call(v),
                .err => |e| .{ .err = e },
            };
        }
    };
}
fn _pad_fill(fill: anytype) u8 {
    if (comptime @typeInfo(@TypeOf(fill)) == .pointer) return fill[0];
    return @as(u8, @intCast(fill));
}
fn _pad_left(s: []const u8, width: usize, fill: anytype, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], _pad_fill(fill));
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: anytype, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], _pad_fill(fill));
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: anytype, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], _pad_fill(fill));
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], _pad_fill(fill));
    return buf;
}
fn _zebra_sort_natural(comptime T: type, items: []T) void {
    const _I = struct {
        fn less(_: void, a: T, b: T) bool {
            if (comptime T == []const u8) return std.mem.lessThan(u8, a, b);
            return a < b;
        }
    };
    std.mem.sort(T, items, {}, _I.less);
}
fn _zebra_sort_by(comptime T: type, comptime cmp: anytype, items: []T) void {
    const _I = struct {
        fn less(_: void, a: T, b: T) bool {
            return cmp(a, b);
        }
    };
    std.mem.sort(T, items, {}, _I.less);
}
const SysRunResult = struct { exit_code: i64, stdout: []const u8, stderr: []const u8 };
fn _sys_run(argv: std.ArrayList([]const u8)) SysRunResult {
    const _r = std.process.Child.run(.{
        .allocator = _allocator,
        .argv = argv.items,
        .max_output_bytes = 16 * 1024 * 1024,
    }) catch return SysRunResult{ .exit_code = -1, .stdout = "", .stderr = "spawn failed" };
    const _ec: i64 = switch (_r.term) {
        .Exited => |code| @intCast(code),
        else    => -1,
    };
    return .{ .exit_code = _ec, .stdout = _r.stdout, .stderr = _r.stderr };
}
const _DateTime = struct { epoch_ms: i64 };
const _CalendarView = struct {
    year: i64, month: i64, day: i64, weekday: i64,
    monthName: []const u8, era: []const u8,
};
const _DtG = struct { year: i64, month: i64, day: i64, hour: i64, minute: i64, second: i64 };
fn _dt_is_leap(year: i64) bool {
    return @mod(year, 4) == 0 and (@mod(year, 100) != 0 or @mod(year, 400) == 0);
}
fn _dt_days_in_month(year: i64, month: i64) i64 {
    const _d = [12]i64{ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
    if (month == 2 and _dt_is_leap(year)) return 29;
    return _d[@intCast(month - 1)];
}
fn _dt_to_gregorian(epoch_ms: i64) _DtG {
    const epoch_s   = @divFloor(epoch_ms, 1000);
    const epoch_days = @divFloor(epoch_s, 86400);
    const time_rem  = @mod(epoch_s, 86400);
    // Fliegel-Van Flandern: JDN → civil Gregorian date
    const jd = epoch_days + 2440588;
    var l  = jd + 68569;
    const n  = @divFloor(4 * l, 146097);
    l = l - @divFloor(146097 * n + 3, 4);
    const ii = @divFloor(4000 * (l + 1), 1461001);
    l = l - @divFloor(1461 * ii, 4) + 31;
    const jj = @divFloor(80 * l, 2447);
    const day   = l - @divFloor(2447 * jj, 80);
    l = @divFloor(jj, 11);
    const month = jj + 2 - 12 * l;
    const year  = 100 * (n - 49) + ii + l;
    return .{
        .year = year, .month = month, .day = day,
        .hour   = @divFloor(time_rem, 3600),
        .minute = @divFloor(@mod(time_rem, 3600), 60),
        .second = @mod(time_rem, 60),
    };
}
fn _dt_from_gregorian(year: i64, month: i64, day: i64, hour: i64, minute: i64, second: i64) _DateTime {
    // Richards algorithm: civil date → JDN
    const a   = @divFloor(14 - month, 12);
    const y   = year + 4800 - a;
    const m   = month + 12 * a - 3;
    const jdn = day + @divFloor(153 * m + 2, 5) + 365 * y
              + @divFloor(y, 4) - @divFloor(y, 100) + @divFloor(y, 400) - 32045;
    const epoch_days = jdn - 2440588;
    const epoch_s    = epoch_days * 86400 + hour * 3600 + minute * 60 + second;
    return .{ .epoch_ms = epoch_s * 1000 };
}
fn _dt_now() _DateTime { return .{ .epoch_ms = std.time.milliTimestamp() }; }
fn _dt_weekday(dt: _DateTime) i64 {
    // epoch_days=0 is Thursday (ISO 4); Monday=1 … Sunday=7
    const epoch_days = @divFloor(dt.epoch_ms, 86400000);
    return @mod(epoch_days + 3, 7) + 1;
}
fn _dt_add_days(dt: _DateTime, n: i64) _DateTime    { return .{ .epoch_ms = dt.epoch_ms + n * 86400000 }; }
fn _dt_add_hours(dt: _DateTime, n: i64) _DateTime   { return .{ .epoch_ms = dt.epoch_ms + n * 3600000 }; }
fn _dt_add_minutes(dt: _DateTime, n: i64) _DateTime { return .{ .epoch_ms = dt.epoch_ms + n * 60000 }; }
fn _dt_add_seconds(dt: _DateTime, n: i64) _DateTime { return .{ .epoch_ms = dt.epoch_ms + n * 1000 }; }
fn _dt_add_months(dt: _DateTime, months: i64) _DateTime {
    const g      = _dt_to_gregorian(dt.epoch_ms);
    const total  = (g.month - 1) + months;
    const ny     = g.year + @divFloor(total, 12);
    const nm     = @mod(total, 12) + 1;
    const max_d  = _dt_days_in_month(ny, nm);
    const nd     = if (g.day > max_d) max_d else g.day;
    return _dt_from_gregorian(ny, nm, nd, g.hour, g.minute, g.second);
}
fn _dt_add_years(dt: _DateTime, years: i64) _DateTime {
    const g     = _dt_to_gregorian(dt.epoch_ms);
    const ny    = g.year + years;
    const max_d = _dt_days_in_month(ny, g.month);
    const nd    = if (g.day > max_d) max_d else g.day;
    return _dt_from_gregorian(ny, g.month, nd, g.hour, g.minute, g.second);
}
fn _dt_to_iso8601(dt: _DateTime) []const u8 {
    const g = _dt_to_gregorian(dt.epoch_ms);
    return std.fmt.allocPrint(_allocator,
        "{d:0>4}-{d:0>2}-{d:0>2}T{d:0>2}:{d:0>2}:{d:0>2}Z",
        .{ @as(u32, @intCast(g.year)), @as(u8, @intCast(g.month)), @as(u8, @intCast(g.day)),
           @as(u8, @intCast(g.hour)),  @as(u8, @intCast(g.minute)), @as(u8, @intCast(g.second)) }) catch "";
}
fn _dt_format(dt: _DateTime, pattern: []const u8) []const u8 {
    const g = _dt_to_gregorian(dt.epoch_ms);
    const _sm = [_][]const u8{"","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};
    const _lm = [_][]const u8{"","January","February","March","April","May","June","July","August","September","October","November","December"};
    const _sw = [_][]const u8{"","Mon","Tue","Wed","Thu","Fri","Sat","Sun"};
    const _lw = [_][]const u8{"","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};
    var out: std.ArrayListUnmanaged(u8) = .{};
    var tmp: [32]u8 = undefined;
    var i: usize = 0;
    while (i < pattern.len) {
        const c = pattern[i];
        var cnt: usize = 1;
        while (i + cnt < pattern.len and pattern[i + cnt] == c) cnt += 1;
        const _uy = @as(u32, @intCast(g.year));
        const _um = @as(u8,  @intCast(g.month));
        const _ud = @as(u8,  @intCast(g.day));
        const _uh = @as(u8,  @intCast(g.hour));
        const _umin = @as(u8, @intCast(g.minute));
        const _us = @as(u8,  @intCast(g.second));
        switch (c) {
            'y' => if (cnt >= 4) out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>4}", .{_uy}) catch "") catch {}
                   else out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_uy % 100}) catch "") catch {},
            'M' => if (cnt >= 4) out.appendSlice(_allocator, _lm[@intCast(g.month)]) catch {}
                   else if (cnt >= 3) out.appendSlice(_allocator, _sm[@intCast(g.month)]) catch {}
                   else if (cnt >= 2) out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_um}) catch "") catch {}
                   else out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d}", .{_um}) catch "") catch {},
            'd' => if (cnt >= 2) out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_ud}) catch "") catch {}
                   else out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d}", .{_ud}) catch "") catch {},
            'H' => out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_uh}) catch "") catch {},
            'm' => out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_umin}) catch "") catch {},
            's' => out.appendSlice(_allocator, std.fmt.bufPrint(&tmp, "{d:0>2}", .{_us}) catch "") catch {},
            'E' => { const _wd: usize = @intCast(_dt_weekday(dt)); out.appendSlice(_allocator, if (cnt >= 4) _lw[_wd] else _sw[_wd]) catch {}; },
            else => out.appendNTimes(_allocator, c, cnt) catch {},
        }
        i += cnt;
    }
    return out.toOwnedSlice(_allocator) catch "";
}
fn _dt_days_between(a: _DateTime, b: _DateTime) i64    { return @divFloor(b.epoch_ms - a.epoch_ms, 86400000); }
fn _dt_seconds_between(a: _DateTime, b: _DateTime) i64 { return @divFloor(b.epoch_ms - a.epoch_ms, 1000); }
fn _dt_in_calendar(dt: _DateTime, cal: []const u8) _CalendarView {
    _ = cal; // only Gregorian implemented; future: dispatch on cal
    const g  = _dt_to_gregorian(dt.epoch_ms);
    const _lm2 = [_][]const u8{"","January","February","March","April","May","June","July","August","September","October","November","December"};
    return .{
        .year = g.year, .month = g.month, .day = g.day,
        .weekday   = _dt_weekday(dt),
        .monthName = _lm2[@intCast(g.month)],
        .era       = "",
    };
}
const Calendar = struct {
    pub const Gregorian = "gregorian";
    pub const Hebrew    = "hebrew";
    pub const Islamic   = "islamic";
    pub const Persian   = "persian";
    pub const Julian    = "julian";
};
const JsonValue = std.json.Value;
fn _json_parse(src: []const u8) ?JsonValue {
    // parseFromSliceLeaky uses allocator directly (no arena), intentionally leaked.
    return std.json.parseFromSliceLeaky(JsonValue, std.heap.page_allocator, src, .{}) catch return null;
}
fn _json_stringify(v: JsonValue) []const u8 {
    return std.json.Stringify.valueAlloc(std.heap.page_allocator, v, .{}) catch "{}";
}
fn _json_object() JsonValue { return .{ .object = std.json.ObjectMap.init(std.heap.page_allocator) }; }
fn _json_array() JsonValue  { return .{ .array = std.json.Array.init(std.heap.page_allocator) }; }
fn _json_get_str(v: JsonValue, key: []const u8) []const u8 {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) { .string => |s| return s, else => {} }, else => {} }
    return "";
}
fn _json_get_int(v: JsonValue, key: []const u8) i64 {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) { .integer => |n| return n, else => {} }, else => {} }
    return 0;
}
fn _json_get_float(v: JsonValue, key: []const u8) f64 {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) {
        .float => |f| return f, .integer => |n| return @floatFromInt(n), else => {} }, else => {} }
    return 0.0;
}
fn _json_get_bool(v: JsonValue, key: []const u8) bool {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) { .bool => |b| return b, else => {} }, else => {} }
    return false;
}
fn _json_get_obj(v: JsonValue, key: []const u8) JsonValue {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) { .object => return it, else => {} }, else => {} }
    return .{ .object = std.json.ObjectMap.init(std.heap.page_allocator) };
}
fn _json_get_list(v: JsonValue, key: []const u8) []JsonValue {
    switch (v) { .object => |o| if (o.get(key)) |it| switch (it) { .array => |a| return a.items, else => {} }, else => {} }
    return &[_]JsonValue{};
}
fn _json_is_null(v: JsonValue) bool   { return v == .null; }
fn _json_is_object(v: JsonValue) bool  { return switch (v) { .object => true, else => false }; }
fn _json_is_array(v: JsonValue) bool   { return switch (v) { .array  => true, else => false }; }
fn _json_put_str(v: *JsonValue, key: []const u8, val: []const u8) void {
    if (v.* != .object) return;
    v.object.put(std.heap.page_allocator.dupe(u8, key) catch return, .{ .string = val }) catch {};
}
fn _json_put_int(v: *JsonValue, key: []const u8, val: i64) void {
    if (v.* != .object) return;
    v.object.put(std.heap.page_allocator.dupe(u8, key) catch return, .{ .integer = val }) catch {};
}
fn _json_put_float(v: *JsonValue, key: []const u8, val: f64) void {
    if (v.* != .object) return;
    v.object.put(std.heap.page_allocator.dupe(u8, key) catch return, .{ .float = val }) catch {};
}
fn _json_put_bool(v: *JsonValue, key: []const u8, val: bool) void {
    if (v.* != .object) return;
    v.object.put(std.heap.page_allocator.dupe(u8, key) catch return, .{ .bool = val }) catch {};
}
fn _json_arr_str(v: *JsonValue, val: []const u8) void {
    if (v.* != .array) return;
    v.array.append(.{ .string = val }) catch {};
}
fn _json_arr_int(v: *JsonValue, val: i64) void {
    if (v.* != .array) return;
    v.array.append(.{ .integer = val }) catch {};
}
fn _json_arr_float(v: *JsonValue, val: f64) void {
    if (v.* != .array) return;
    v.array.append(.{ .float = val }) catch {};
}
fn _json_arr_bool(v: *JsonValue, val: bool) void {
    if (v.* != .array) return;
    v.array.append(.{ .bool = val }) catch {};
}
const HttpResponse = struct { status: u16, text: []const u8, headers: []const [2][]const u8 = &.{} };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) ?HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch return null;
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) ?HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) ?HttpResponse { return _http_request(.POST, url, payload); }
fn _http_json_get(url: []const u8) ?JsonValue { const _r = _http_request(.GET, url, null) orelse return null; return _json_parse(_r.text); }
fn _http_json_post(url: []const u8, body: []const u8) ?JsonValue {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    _ = _hc.fetch(.{ .location = .{ .url = url }, .method = .POST, .payload = body,
        .extra_headers = &.{ .{ .name = "Content-Type", .value = "application/json" } },
        .response_writer = &_hb.writer }) catch return null;
    return _json_parse(_hb.written());
}
fn _http_with_header(resp: HttpResponse, key: []const u8, val: []const u8) HttpResponse {
    var _new = std.heap.page_allocator.alloc([2][]const u8, resp.headers.len + 1) catch return resp;
    @memcpy(_new[0..resp.headers.len], resp.headers);
    _new[resp.headers.len] = .{ key, val };
    return .{ .status = resp.status, .text = resp.text, .headers = _new };
}
const HttpRequest = struct { method: []const u8, path: []const u8, content: []const u8 };
fn _http_serve(port: u16, handler: anytype) void {
    const _HFn = *const fn(HttpRequest) HttpResponse;
    const _fn: _HFn = handler;
    const _Ctx = struct {
        conn: std.net.Server.Connection,
        handler_fn: _HFn,
        fn run(ctx: *@This()) void {
            defer std.heap.page_allocator.destroy(ctx);
            defer ctx.conn.stream.close();
            const _alloc = std.heap.page_allocator;
            // Read request headers (scan for \r\n\r\n).
            var _hd: [16384]u8 = undefined;
            var _hl: usize = 0;
            while (_hl < _hd.len - 4096) {
                const _n = std.posix.recv(ctx.conn.stream.handle, _hd[_hl..@min(_hl+4096, _hd.len)], 0) catch break;
                if (_n == 0) break;
                _hl += _n;
                if (std.mem.indexOf(u8, _hd[0.._hl], "\r\n\r\n") != null) break;
            }
            const _hdrs_end = (std.mem.indexOf(u8, _hd[0.._hl], "\r\n\r\n") orelse (_hl -| 4)) + 4;
            const _head = _hd[0.._hdrs_end];
            var _peeked: usize = if (_hl > _hdrs_end) _hl - _hdrs_end else 0;
            // Parse request line: METHOD PATH VERSION
            const _rl_end = std.mem.indexOf(u8, _head, "\r\n") orelse _hl;
            var _rp = std.mem.splitScalar(u8, _head[0.._rl_end], ' ');
            const _method = _rp.next() orelse "GET";
            const _raw_path = _rp.next() orelse "/";
            const _path = _raw_path[0 .. (std.mem.indexOfScalar(u8, _raw_path, '?') orelse _raw_path.len)];
            // Parse Content-Length.
            var _cl: usize = 0;
            var _hdr_it = std.mem.splitSequence(u8, _head, "\r\n");
            _ = _hdr_it.next();
            while (_hdr_it.next()) |_hl_| {
                if (_hl_.len == 0) break;
                const _cp = std.mem.indexOfScalar(u8, _hl_, ':') orelse continue;
                const _hn = std.mem.trim(u8, _hl_[0.._cp], " ");
                const _hv = std.mem.trim(u8, _hl_[_cp+1..], " ");
                if (std.ascii.eqlIgnoreCase(_hn, "content-length"))
                    _cl = std.fmt.parseInt(usize, _hv, 10) catch 0;
            }
            var _body: []const u8 = "";
            if (_cl > 0) {
                const _bb = _alloc.alloc(u8, _cl) catch @panic("OOM");
                const _pre = @min(_peeked, _cl);
                if (_pre > 0) @memcpy(_bb[0.._pre], _hd[_hdrs_end.._hdrs_end+_pre]);
                var _bi: usize = _pre;
                while (_bi < _cl) {
                    const _rn = std.posix.recv(ctx.conn.stream.handle, _bb[_bi..], 0) catch break;
                    if (_rn == 0) break;
                    _bi += _rn;
                }
                _body = _bb[0.._bi];
                _ = &_peeked;
            }
            const _req = HttpRequest{ .method = _method, .path = _path, .content = _body };
            const _resp = ctx.handler_fn(_req);
            const _st: []const u8 = switch (_resp.status) {
                200 => "OK", 201 => "Created", 204 => "No Content",
                301 => "Moved Permanently", 302 => "Found",
                400 => "Bad Request", 401 => "Unauthorized", 403 => "Forbidden",
                404 => "Not Found", 405 => "Method Not Allowed",
                500 => "Internal Server Error",
                else => "Unknown",
            };
            var _xh: std.ArrayList(u8) = .{};
            for (_resp.headers) |_kv| { _xh.appendSlice(_alloc, _kv[0]) catch {}; _xh.appendSlice(_alloc, ": ") catch {}; _xh.appendSlice(_alloc, _kv[1]) catch {}; _xh.appendSlice(_alloc, "\r\n") catch {}; }
            const _out = std.fmt.allocPrint(_alloc,
                "HTTP/1.1 {d} {s}\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {d}\r\nConnection: close\r\n{s}\r\n{s}",
                .{ _resp.status, _st, _resp.text.len, _xh.items, _resp.text }) catch @panic("OOM");
            ctx.conn.stream.writeAll(_out) catch {};
        }
    };
    const _alloc = std.heap.page_allocator;
    var _srv = std.net.Address.initIp4(.{ 0, 0, 0, 0 }, port).listen(.{ .reuse_address = true }) catch |e| @panic(@errorName(e));
    defer _srv.deinit();
    while (true) {
        const _conn = _srv.accept() catch continue;
        const _ctx = _alloc.create(_Ctx) catch { _conn.stream.close(); continue; };
        _ctx.* = .{ .conn = _conn, .handler_fn = _fn };
        _ = std.Thread.spawn(.{}, _Ctx.run, .{_ctx}) catch {
            _alloc.destroy(_ctx);
            _conn.stream.close();
        };
    }
}

const _CsvTable = struct { rows: []const []const []const u8 };
fn _csv_parse(src: []const u8) _CsvTable {
    const _pa = std.heap.page_allocator;
    var _rows: std.ArrayList([]const []const u8) = .{};
    var _row:  std.ArrayList([]const u8) = .{};
    var _f:    std.ArrayList(u8) = .{};
    const _St = enum { s, fld, q, aq };
    var _st: _St = .s;
    for (src) |c| {
        switch (_st) {
            .s => switch (c) {
                '"'  => { _st = .q; },
                ','  => { _row.append(_pa, "") catch {}; },
                '\r' => {},
                '\n' => { if (_row.items.len > 0) { _rows.append(_pa, _row.toOwnedSlice(_pa) catch &.{}) catch {}; _row = .{}; } },
                else => { _f.append(_pa, c) catch {}; _st = .fld; },
            },
            .fld => switch (c) {
                ',' => { _row.append(_pa, _f.toOwnedSlice(_pa) catch "") catch {}; _f = .{}; _st = .s; },
                '\r' => {},
                '\n' => { _row.append(_pa, _f.toOwnedSlice(_pa) catch "") catch {}; _f = .{}; _rows.append(_pa, _row.toOwnedSlice(_pa) catch &.{}) catch {}; _row = .{}; _st = .s; },
                else => { _f.append(_pa, c) catch {}; },
            },
            .q  => switch (c) {
                '"'  => { _st = .aq; },
                else => { _f.append(_pa, c) catch {}; },
            },
            .aq => switch (c) {
                '"' => { _f.append(_pa, '"') catch {}; _st = .q; },
                ',' => { _row.append(_pa, _f.toOwnedSlice(_pa) catch "") catch {}; _f = .{}; _st = .s; },
                '\r' => {},
                '\n' => { _row.append(_pa, _f.toOwnedSlice(_pa) catch "") catch {}; _f = .{}; _rows.append(_pa, _row.toOwnedSlice(_pa) catch &.{}) catch {}; _row = .{}; _st = .s; },
                else => { _st = .s; },
            },
        }
    }
    if (_st == .fld or _st == .aq or _st == .q) {
        _row.append(_pa, _f.toOwnedSlice(_pa) catch "") catch {};
    } else if (_st == .s and _row.items.len > 0) {
        _row.append(_pa, "") catch {};
    }
    if (_row.items.len > 0) _rows.append(_pa, _row.toOwnedSlice(_pa) catch &.{}) catch {};
    return .{ .rows = _rows.toOwnedSlice(_pa) catch &.{} };
}
fn _csv_parse_file(path: []const u8) _CsvTable {
    const src = std.fs.cwd().readFileAlloc(std.heap.page_allocator, path, std.math.maxInt(usize)) catch return .{ .rows = &.{} };
    return _csv_parse(src);
}
fn _csv_row_count(t: _CsvTable) i64 { return @as(i64, @intCast(t.rows.len)); }
fn _csv_col_count(t: _CsvTable) i64 { return if (t.rows.len > 0) @as(i64, @intCast(t.rows[0].len)) else 0; }
fn _csv_header(t: _CsvTable) std.ArrayList([]const u8) {
    var _r: std.ArrayList([]const u8) = .{};
    if (t.rows.len > 0) for (t.rows[0]) |f| _r.append(std.heap.page_allocator, f) catch {};
    return _r;
}
fn _csv_row(t: _CsvTable, n: i64) std.ArrayList([]const u8) {
    var _r: std.ArrayList([]const u8) = .{};
    const _i: usize = @intCast(@max(0, n));
    if (_i < t.rows.len) for (t.rows[_i]) |f| _r.append(std.heap.page_allocator, f) catch {};
    return _r;
}
fn _csv_rows(t: _CsvTable) std.ArrayList(std.ArrayList([]const u8)) {
    var _out: std.ArrayList(std.ArrayList([]const u8)) = .{};
    for (t.rows) |row| { var _r: std.ArrayList([]const u8) = .{}; for (row) |f| _r.append(std.heap.page_allocator, f) catch {}; _out.append(std.heap.page_allocator, _r) catch {}; }
    return _out;
}
fn _csv_data_rows(t: _CsvTable) std.ArrayList(std.ArrayList([]const u8)) {
    var _out: std.ArrayList(std.ArrayList([]const u8)) = .{};
    const _s: usize = if (t.rows.len > 0) 1 else 0;
    for (t.rows[_s..]) |row| { var _r: std.ArrayList([]const u8) = .{}; for (row) |f| _r.append(std.heap.page_allocator, f) catch {}; _out.append(std.heap.page_allocator, _r) catch {}; }
    return _out;
}
fn _csv_get(t: _CsvTable, row: std.ArrayList([]const u8), col: []const u8) []const u8 {
    if (t.rows.len == 0) return "";
    for (t.rows[0], 0..) |h, i| { if (std.mem.eql(u8, h, col)) return if (i < row.items.len) row.items[i] else ""; }
    return "";
}
const _CsvWriter = struct { buf: std.ArrayList(u8) };
fn _csv_writer_init() _CsvWriter { return .{ .buf = .{} }; }
fn _csv_write_row(w: *_CsvWriter, row: std.ArrayList([]const u8)) void {
    const _pa = std.heap.page_allocator;
    for (row.items, 0..) |field, i| {
        if (i > 0) w.buf.append(_pa, ',') catch {};
        const _nq = std.mem.indexOfAny(u8, field, ",\"\r\n") != null;
        if (_nq) {
            w.buf.append(_pa, '"') catch {};
            for (field) |c| { if (c == '"') w.buf.append(_pa, '"') catch {}; w.buf.append(_pa, c) catch {}; }
            w.buf.append(_pa, '"') catch {};
        } else { w.buf.appendSlice(_pa, field) catch {}; }
    }
    w.buf.appendSlice(_pa, "\r\n") catch {};
}
fn _csv_build(w: *const _CsvWriter) []const u8 { return w.buf.items; }
const TcpConn = struct { stream: std.net.Stream };
fn _tcp_connect(host: []const u8, port: u16) ?TcpConn {
    const s = std.net.tcpConnectToHost(_allocator, host, port) catch return null;
    return .{ .stream = s };
}
fn _tcp_write(conn: TcpConn, data: []const u8) void {
    conn.stream.writeAll(data) catch |e| @panic(@errorName(e));
}
fn _tcp_read(conn: TcpConn) []const u8 {
    var _rb: [65536]u8 = undefined;
    var _rd = conn.stream.reader(&_rb);
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    _ = _rd.interface().streamRemaining(&_hb.writer) catch |e| @panic(@errorName(e));
    return _hb.written();
}
fn _tcp_read_line(conn: TcpConn) []const u8 {
    var _buf: std.ArrayList(u8) = .{};
    while (true) {
        var _b: [1]u8 = undefined;
        const _n = std.posix.recv(conn.stream.handle, &_b, 0) catch break;
        if (_n == 0) break;
        if (_b[0] == '\n') break;
        if (_b[0] != '\r') _buf.append(std.heap.page_allocator, _b[0]) catch break;
    }
    return _buf.items;
}
fn _tcp_read_bytes(conn: TcpConn, n: usize) []const u8 {
    const _buf = std.heap.page_allocator.alloc(u8, n) catch @panic("OOM");
    var _total: usize = 0;
    while (_total < n) {
        const _got = std.posix.recv(conn.stream.handle, _buf[_total..], 0) catch break;
        if (_got == 0) break;
        _total += _got;
    }
    return _buf[0.._total];
}
fn _tcp_close(conn: TcpConn) void { conn.stream.close(); }

const UdpSocket = struct { handle: std.posix.socket_t };
fn _udp_socket() UdpSocket {
    const s = std.posix.socket(std.posix.AF.INET, std.posix.SOCK.DGRAM, 0) catch |e| @panic(@errorName(e));
    return .{ .handle = s };
}
fn _udp_send(sock: UdpSocket, host: []const u8, port: u16, data: []const u8) void {
    const dest = blk: {
        if (std.net.Address.parseIp(host, port)) |a| break :blk a else |_| {}
        const _list = std.net.getAddressList(std.heap.page_allocator, host, port) catch |e| @panic(@errorName(e));
        defer _list.deinit();
        if (_list.addrs.len == 0) @panic("UDP send: hostname resolution failed");
        break :blk _list.addrs[0];
    };
    _ = std.posix.sendto(sock.handle, data, 0, &dest.any, dest.getOsSockLen()) catch |e| @panic(@errorName(e));
}
fn _udp_recv(sock: UdpSocket, max_bytes: usize) []const u8 {
    const buf = std.heap.page_allocator.alloc(u8, max_bytes) catch @panic("OOM");
    const n = std.posix.recv(sock.handle, buf, 0) catch |e| @panic(@errorName(e));
    return buf[0..n];
}
fn _udp_close(sock: UdpSocket) void { std.posix.close(sock.handle); }

fn _net_resolve(host: []const u8) []const []const u8 {
    var _result: std.ArrayList([]const u8) = .{};
    const _list = std.net.getAddressList(std.heap.page_allocator, host, 0) catch return &.{};
    defer _list.deinit();
    for (_list.addrs) |_addr| {
        var _buf: [64]u8 = undefined;
        const _full = std.fmt.bufPrint(&_buf, "{f}", .{_addr}) catch continue;
        const _col = std.mem.lastIndexOfScalar(u8, _full, ':') orelse _full.len;
        var _ip = _full[0.._col];
        if (_ip.len >= 2 and _ip[0] == '[') _ip = _ip[1 .. _ip.len - 1];
        const _owned = std.heap.page_allocator.dupe(u8, _ip) catch continue;
        _result.append(std.heap.page_allocator, _owned) catch {};
    }
    return _result.toOwnedSlice(std.heap.page_allocator) catch &.{};
}
// ─── Thompson NFA regex engine ───────────────────────────────────────────────
const _RNodeKind = enum(u8) { match, lit, dot, cls, split, save, bol, eol_a, wb };
const _RNode = struct {
    kind: _RNodeKind, c: u8 = 0, bits: [32]u8 = [_]u8{0} ** 32,
    neg: bool = false, slot: u8 = 0, out1: u32 = 0xFFFF_FFFF, out2: u32 = 0xFFFF_FFFF,
};
const _RFlags = struct {
    ignore_case: bool = false, multiline: bool = false, dot_all: bool = false, unlimited: bool = false,
    lazy_match: bool = false, // set when any *? +? ?? is parsed
};
const _RFrag = struct {
    start: u32, outs: [64]u32 = [_]u32{0xFFFF_FFFF} ** 64, n: u8 = 0,
    fn one(s: u32, d: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d; f.n = 1; return f; }
    fn two(s: u32, d1: u32, d2: u32) _RFrag { var f = _RFrag{ .start = s }; f.outs[0] = d1; f.outs[1] = d2; f.n = 2; return f; }
    fn merge(a: _RFrag, b: _RFrag) _RFrag {
        var f = _RFrag{ .start = a.start }; var i: u8 = 0;
        for (a.outs[0..a.n]) |o| { f.outs[i] = o; i += 1; }
        for (b.outs[0..b.n]) |o| { f.outs[i] = o; i += 1; }
        f.n = i; return f;
    }
};
const _RC = struct {
    pat: []const u8, pos: usize = 0,
    nodes: std.ArrayListUnmanaged(_RNode) = .{}, alloc: std.mem.Allocator, n_caps: u8 = 0, flags: _RFlags = .{},
    fn addNode(c: *_RC, n: _RNode) error{OutOfMemory}!u32 {
        const idx: u32 = @intCast(c.nodes.items.len);
        try c.nodes.append(c.alloc, n); return idx;
    }
    fn patch(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| c.nodes.items[i & 0x7FFF_FFFF].out1 = t;
    }
    fn patchFrag(c: *_RC, f: _RFrag, t: u32) void {
        for (f.outs[0..f.n]) |i| {
            if (i & 0x8000_0000 != 0) c.nodes.items[i & 0x7FFF_FFFF].out2 = t
            else c.nodes.items[i].out1 = t;
        }
    }
    fn peek(c: *_RC) ?u8 { return if (c.pos < c.pat.len) c.pat[c.pos] else null; }
    fn eat(c: *_RC) ?u8 { if (c.pos < c.pat.len) { defer c.pos += 1; return c.pat[c.pos]; } return null; }
    fn expect(c: *_RC, ch: u8) bool { if (c.peek() == ch) { c.pos += 1; return true; } return false; }
    fn parseClass(c: *_RC) error{OutOfMemory}![32]u8 {
        var bits = [_]u8{0} ** 32;
        while (c.peek()) |ch| {
            if (ch == ']') break; _ = c.eat();
            if (ch == '\\') { const esc = c.eat() orelse break; _rSetEsc(&bits, esc); }
            else if (c.peek() == '-' and c.pos + 1 < c.pat.len and c.pat[c.pos + 1] != ']') {
                _ = c.eat(); const hi = c.eat() orelse ch;
                var i: u8 = ch; while (true) : (i += 1) { _rSetBit(&bits, i); if (i == hi) break; }
            } else _rSetBit(&bits, ch);
        } return bits;
    }
    fn parseAtom(c: *_RC) error{OutOfMemory}!?_RFrag {
        const ch = c.peek() orelse return null;
        switch (ch) {
            '^' => { _ = c.eat(); const idx = try c.addNode(.{ .kind = .bol }); return _RFrag.one(idx, idx); },
            '$' => { _ = c.eat(); const idx = try c.addNode(.{ .kind = .eol_a }); return _RFrag.one(idx, idx); },
            '(' => {
                _ = c.eat();
                // Non-capturing group (?:...)
                if (c.peek() == '?' and c.pos + 1 < c.pat.len and c.pat[c.pos + 1] == ':') {
                    c.pos += 2;
                    if (try c.parseAlt()) |inner| { _ = c.expect(')'); return inner; }
                    _ = c.expect(')'); return null;
                }
                // Capturing group
                const slot: u8 = c.n_caps * 2; c.n_caps += 1;
                const open = try c.addNode(.{ .kind = .save, .slot = slot });
                if (try c.parseAlt()) |inner| {
                    c.patchFrag(inner, try c.addNode(.{ .kind = .save, .slot = slot + 1 }));
                    _ = c.expect(')');
                    const close: u32 = @intCast(c.nodes.items.len - 1);
                    c.nodes.items[open].out1 = inner.start;
                    return _RFrag.one(open, close);
                }
                _ = c.expect(')'); return _RFrag.one(open, open);
            },
            ')', '|' => return null,
            '[' => {
                _ = c.eat(); const neg = c.expect('^');
                const bits = try c.parseClass(); _ = c.expect(']');
                const idx = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = neg });
                return _RFrag.one(idx, idx);
            },
            '.' => { _ = c.eat(); const _di = try c.addNode(.{ .kind = .dot }); return _RFrag.one(_di, _di); },
            '\\' => {
                _ = c.eat(); const esc = c.eat() orelse return null;
                // \b / \B are zero-width word-boundary assertions, not char classes
                if (esc == 'b' or esc == 'B') {
                    const idx = try c.addNode(.{ .kind = .wb, .neg = (esc == 'B') });
                    return _RFrag.one(idx, idx);
                }
                var bits = [_]u8{0} ** 32;
                const neg = std.ascii.isUpper(esc);
                if (neg) { _rSetEsc(&bits, std.ascii.toLower(esc)); const pb = bits; bits = [_]u8{0} ** 32; for (&bits, pb) |*b, p| b.* = ~p; }
                else _rSetEsc(&bits, esc);
                const _ci = try c.addNode(.{ .kind = .cls, .bits = bits, .neg = false });
                return _RFrag.one(_ci, _ci);
            },
            else => { _ = c.eat(); const idx = try c.addNode(.{ .kind = .lit, .c = ch }); return _RFrag.one(idx, idx); },
        }
    }
    fn parsePieceFixed(c: *_RC) error{OutOfMemory}!?_RFrag {
        const atom_pos = c.pos;
        const atom = try c.parseAtom() orelse return null;
        const q = c.peek() orelse return atom;
        switch (q) {
            '*' => {
                _ = c.eat(); const lazy = c.expect('?');
                if (lazy) c.flags.lazy_match = true;
                const sp = try c.addNode(.{ .kind = .split,
                    .out1 = if (lazy) 0xFFFF_FFFF else atom.start,
                    .out2 = if (lazy) atom.start  else 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = sp };
                f.outs[0] = if (lazy) sp else sp | 0x8000_0000; f.n = 1; return f;
            },
            '+' => {
                _ = c.eat(); const lazy = c.expect('?');
                if (lazy) c.flags.lazy_match = true;
                const sp = try c.addNode(.{ .kind = .split,
                    .out1 = if (lazy) 0xFFFF_FFFF else atom.start,
                    .out2 = if (lazy) atom.start  else 0xFFFF_FFFF });
                c.patch(atom, sp);
                var f = _RFrag{ .start = atom.start };
                f.outs[0] = if (lazy) sp else sp | 0x8000_0000; f.n = 1; return f;
            },
            '?' => {
                _ = c.eat(); const lazy = c.expect('?');
                if (lazy) c.flags.lazy_match = true;
                const sp = try c.addNode(.{ .kind = .split,
                    .out1 = if (lazy) 0xFFFF_FFFF else atom.start,
                    .out2 = if (lazy) atom.start  else 0xFFFF_FFFF });
                return if (lazy) _RFrag.two(sp, sp, atom.outs[0])
                       else      _RFrag.two(sp, atom.outs[0], sp | 0x8000_0000);
            },
            '{' => {
                _ = c.eat();
                var n: u32 = 0;
                while (c.peek()) |d| { if (d < '0' or d > '9') break; n = n *% 10 +% (d - '0'); _ = c.eat(); }
                var m: u32 = n; var unbounded = false;
                if (c.expect(',')) {
                    if (c.peek() == '}') { unbounded = true; }
                    else { m = 0; while (c.peek()) |d| { if (d < '0' or d > '9') break; m = m *% 10 +% (d - '0'); _ = c.eat(); } }
                }
                _ = c.expect('}');
                if (!c.flags.unlimited) { if (n > 100) n = 100; if (m > 100) m = 100; }
                if (n == 0 and m == 0 and !unbounded) return atom; // degenerate {0}
                const after_q = c.pos;
                // build result: start with the already-parsed atom (counts as copy 1)
                var result: _RFrag = atom;
                // mandatory copies 2..n
                var i: u32 = 1;
                while (i < n) : (i += 1) {
                    c.pos = atom_pos; const next = try c.parseAtom() orelse break; c.pos = after_q;
                    c.patchFrag(result, next.start);
                    result = .{ .start = result.start, .outs = next.outs, .n = next.n };
                }
                // optional copies n+1..m
                var j: u32 = 0;
                while (j < m -| n) : (j += 1) {
                    c.pos = atom_pos; const next = try c.parseAtom() orelse break; c.pos = after_q;
                    const sp = try c.addNode(.{ .kind = .split, .out1 = next.start, .out2 = 0xFFFF_FFFF });
                    c.patchFrag(result, sp);
                    var f2 = _RFrag{ .start = result.start }; f2.outs[0] = next.outs[0]; f2.outs[1] = sp | 0x8000_0000; f2.n = 2; result = f2;
                }
                // unbounded: add * at end
                if (unbounded) {
                    c.pos = atom_pos; const last_a = try c.parseAtom() orelse { c.pos = after_q; return result; }; c.pos = after_q;
                    const sp = try c.addNode(.{ .kind = .split, .out1 = last_a.start, .out2 = 0xFFFF_FFFF });
                    c.patch(last_a, sp);
                    c.patchFrag(result, sp);
                    var f3 = _RFrag{ .start = result.start }; f3.outs[0] = sp | 0x8000_0000; f3.n = 1; return f3;
                }
                return result;
            },
            else => return atom,
        }
    }
    fn parsePiece(c: *_RC) error{OutOfMemory}!?_RFrag { return c.parsePieceFixed(); }
    fn parseCat(c: *_RC) error{OutOfMemory}!?_RFrag {
        var result: ?_RFrag = try c.parsePiece();
        while (result != null) {
            const next = try c.parsePiece() orelse break;
            c.patchFrag(result.?, next.start);
            result = _RFrag{ .start = result.?.start, .outs = next.outs, .n = next.n };
        }
        return result;
    }
    fn parseAlt(c: *_RC) error{OutOfMemory}!?_RFrag {
        const left = try c.parseCat() orelse return null;
        if (c.peek() != '|') return left;
        _ = c.eat();
        const right = try c.parseAlt() orelse return left;
        const sp = try c.addNode(.{ .kind = .split, .out1 = left.start, .out2 = right.start });
        return _RFrag.merge(_RFrag{ .start = sp, .outs = left.outs, .n = left.n }, right);
    }
};
const Regex = struct {
    nodes: []_RNode, start: u32, alloc: std.mem.Allocator, flags: _RFlags = .{},
    fn closure(re: *const Regex, cur: *std.ArrayListUnmanaged(u32), vis: []bool, alloc: std.mem.Allocator, idx: u32, pos: usize, input: []const u8) error{OutOfMemory}!void {
        if (idx == 0xFFFF_FFFF or idx >= re.nodes.len or vis[idx]) return;
        vis[idx] = true;
        const nd = &re.nodes[idx];
        switch (nd.kind) {
            .split => { try re.closure(cur, vis, alloc, nd.out1, pos, input); try re.closure(cur, vis, alloc, nd.out2, pos, input); },
            .save  => try re.closure(cur, vis, alloc, nd.out1, pos, input),
            .bol   => {
                const ok = pos == 0 or (re.flags.multiline and pos > 0 and input[pos - 1] == '\n');
                if (ok) try re.closure(cur, vis, alloc, nd.out1, pos, input);
            },
            .eol_a => {
                const ok = pos == input.len or (re.flags.multiline and pos < input.len and input[pos] == '\n');
                if (ok) try re.closure(cur, vis, alloc, nd.out1, pos, input);
            },
            .wb => {
                const pw = pos > 0 and _rIsWord(input[pos - 1]);
                const cw = pos < input.len and _rIsWord(input[pos]);
                if ((pw != cw) != nd.neg) try re.closure(cur, vis, alloc, nd.out1, pos, input);
            },
            else => try cur.append(alloc, idx),
        }
    }
    fn matchAt(re: *const Regex, input: []const u8, from: usize, shortest: bool) error{OutOfMemory}!?usize {
        const alloc = re.alloc;
        var cur: std.ArrayListUnmanaged(u32) = .{}; var nxt: std.ArrayListUnmanaged(u32) = .{};
        defer cur.deinit(alloc); defer nxt.deinit(alloc);
        const vis = try alloc.alloc(bool, re.nodes.len); defer alloc.free(vis);
        @memset(vis, false); try re.closure(&cur, vis, alloc, re.start, from, input);
        var last: ?usize = null;
        for (cur.items) |si| if (re.nodes[si].kind == .match) { last = from; if (shortest) return last; break; };
        var pos = from;
        while (pos < input.len and cur.items.len > 0) : (pos += 1) {
            const ch = input[pos]; nxt.clearRetainingCapacity(); @memset(vis, false);
            for (cur.items) |si| {
                const nd = &re.nodes[si];
                const ok = switch (nd.kind) {
                    .lit => if (re.flags.ignore_case) std.ascii.toLower(nd.c) == std.ascii.toLower(ch) else nd.c == ch,
                    .dot => if (re.flags.dot_all) true else ch != '\n',
                    .cls => if (re.flags.ignore_case) _rClsMatch(nd, ch) or _rClsMatch(nd, std.ascii.toLower(ch)) or _rClsMatch(nd, std.ascii.toUpper(ch)) else _rClsMatch(nd, ch),
                    else => false,
                };
                if (ok) try re.closure(&nxt, vis, alloc, nd.out1, pos + 1, input);
            }
            std.mem.swap(std.ArrayListUnmanaged(u32), &cur, &nxt);
            for (cur.items) |si| if (re.nodes[si].kind == .match) { last = pos + 1; if (shortest) return last; break; };
        }
        return last;
    }
};
fn _rSetBit(bits: *[32]u8, c: u8) void { bits[c >> 3] |= @as(u8, 1) << @intCast(c & 7); }
fn _rGetBit(bits: *const [32]u8, c: u8) bool { return (bits[c >> 3] >> @intCast(c & 7)) & 1 != 0; }
fn _rClsMatch(nd: *const _RNode, c: u8) bool { const h = _rGetBit(&nd.bits, c); return if (nd.neg) !h else h; }
fn _rIsWord(c: u8) bool { return (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9') or c == '_'; }
fn _rSetEsc(bits: *[32]u8, esc: u8) void {
    switch (std.ascii.toLower(esc)) {
        'd' => { var i: u16 = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); },
        'w' => { var i: u16 = 'a'; while (i <= 'z') : (i += 1) _rSetBit(bits, @intCast(i)); i = 'A'; while (i <= 'Z') : (i += 1) _rSetBit(bits, @intCast(i)); i = '0'; while (i <= '9') : (i += 1) _rSetBit(bits, @intCast(i)); _rSetBit(bits, '_'); },
        's' => { for (" \t\n\r") |c| _rSetBit(bits, c); },
        'n' => _rSetBit(bits, '\n'), 'r' => _rSetBit(bits, '\r'), 't' => _rSetBit(bits, '\t'),
        else => _rSetBit(bits, esc),
    }
}
fn _regex_compile(pattern: []const u8, flags_str: []const u8) Regex {
    const alloc = std.heap.page_allocator;
    var flags = _RFlags{};
    for (flags_str) |f| switch (f) {
        'i' => flags.ignore_case = true, 'm' => flags.multiline = true,
        's' => flags.dot_all = true,     'U' => flags.unlimited = true,
        else => {},
    };
    var c = _RC{ .pat = pattern, .alloc = alloc, .flags = flags };
    const frag_opt = c.parseAlt() catch @panic("regex OOM");
    const match_idx = c.addNode(.{ .kind = .match }) catch @panic("regex OOM");
    if (frag_opt) |frag| {
        c.patchFrag(frag, match_idx);
        return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = frag.start, .alloc = alloc, .flags = c.flags };
    }
    return .{ .nodes = c.nodes.toOwnedSlice(alloc) catch @panic("regex OOM"), .start = match_idx, .alloc = alloc, .flags = c.flags };
}
fn _regex_match(re: Regex, input: []const u8) bool {
    const end = re.matchAt(input, 0, false) catch return false;
    return end != null and end.? == input.len;
}
fn _regex_find(re: Regex, input: []const u8) []const u8 {
    var i: usize = 0;
    while (i <= input.len) : (i += 1) {
        if (re.matchAt(input, i, re.flags.lazy_match) catch null) |e| return input[i..e];
    }
    return "";
}
fn _regex_find_all(re: Regex, input: []const u8) []const []const u8 {
    var out: std.ArrayListUnmanaged([]const u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i, re.flags.lazy_match) catch null) |e| {
            out.append(std.heap.page_allocator, input[i..e]) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else i += 1;
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
fn _regex_replace(re: Regex, input: []const u8, sub: []const u8) []const u8 {
    var out: std.ArrayListUnmanaged(u8) = .{};
    var i: usize = 0;
    while (i < input.len) {
        if (re.matchAt(input, i, re.flags.lazy_match) catch null) |e| {
            out.appendSlice(std.heap.page_allocator, sub) catch @panic("OOM");
            i = if (e > i) e else i + 1;
        } else {
            out.append(std.heap.page_allocator, input[i]) catch @panic("OOM");
            i += 1;
        }
    }
    return out.toOwnedSlice(std.heap.page_allocator) catch @panic("OOM");
}
const _MAX_SAVE_SLOTS: usize = 20; // 10 capture groups (open+close slots each)
const _RegThread = struct { state: u32, saves: [_MAX_SAVE_SLOTS]usize };
// Epsilon closure that threads per-state save vectors through the NFA.
// First-wins: if a state is already in cur, later paths are ignored
// (leftmost-greedy semantics).
fn _re_eclosure_s(
    re: *const Regex, cur: *std.ArrayListUnmanaged(_RegThread),
    vis: []bool, alloc: std.mem.Allocator,
    state: u32, saves: [_MAX_SAVE_SLOTS]usize, pos: usize, input: []const u8,
) std.mem.Allocator.Error!void {
    if (state == 0xFFFF_FFFF or state >= re.nodes.len) return;
    if (vis[state]) return;
    vis[state] = true;
    const nd = &re.nodes[state];
    switch (nd.kind) {
        .split => {
            try _re_eclosure_s(re, cur, vis, alloc, nd.out1, saves, pos, input);
            try _re_eclosure_s(re, cur, vis, alloc, nd.out2, saves, pos, input);
        },
        .save => {
            var ns = saves;
            if (nd.slot < _MAX_SAVE_SLOTS) ns[nd.slot] = pos;
            try _re_eclosure_s(re, cur, vis, alloc, nd.out1, ns, pos, input);
        },
        .bol => {
            const ok = pos == 0 or (re.flags.multiline and pos > 0 and input[pos - 1] == '\n');
            if (ok) try _re_eclosure_s(re, cur, vis, alloc, nd.out1, saves, pos, input);
        },
        .eol_a => {
            const ok = pos == input.len or (re.flags.multiline and pos < input.len and input[pos] == '\n');
            if (ok) try _re_eclosure_s(re, cur, vis, alloc, nd.out1, saves, pos, input);
        },
        .wb => {
            const pw = pos > 0 and _rIsWord(input[pos - 1]);
            const cw = pos < input.len and _rIsWord(input[pos]);
            if ((pw != cw) != nd.neg) try _re_eclosure_s(re, cur, vis, alloc, nd.out1, saves, pos, input);
        },
        else => try cur.append(alloc, .{ .state = state, .saves = saves }),
    }
}
fn _re_match_with_saves(re: *const Regex, input: []const u8, from: usize) ?[_MAX_SAVE_SLOTS]usize {
    const alloc = std.heap.page_allocator;
    const empty: [_MAX_SAVE_SLOTS]usize = [_]usize{0xFFFF_FFFF_FFFF_FFFF} ** _MAX_SAVE_SLOTS;
    var cur: std.ArrayListUnmanaged(_RegThread) = .{};
    defer cur.deinit(alloc);
    var nxt: std.ArrayListUnmanaged(_RegThread) = .{};
    defer nxt.deinit(alloc);
    const vis = alloc.alloc(bool, re.nodes.len) catch return null;
    defer alloc.free(vis);
    @memset(vis, false);
    _re_eclosure_s(re, &cur, vis, alloc, re.start, empty, from, input) catch return null;
    var last: ?[_MAX_SAVE_SLOTS]usize = null;
    for (cur.items) |t| { if (re.nodes[t.state].kind == .match) { last = t.saves; if (re.flags.lazy_match) return last; break; } }
    var pos = from;
    while (pos < input.len and cur.items.len > 0) : (pos += 1) {
        const ch = input[pos]; nxt.clearRetainingCapacity(); @memset(vis, false);
        for (cur.items) |t| {
            const nd = &re.nodes[t.state];
            const ok = switch (nd.kind) {
                .lit => if (re.flags.ignore_case) std.ascii.toLower(nd.c) == std.ascii.toLower(ch) else nd.c == ch,
                .dot => if (re.flags.dot_all) true else ch != '\n',
                .cls => if (re.flags.ignore_case) _rClsMatch(nd, ch) or _rClsMatch(nd, std.ascii.toLower(ch)) or _rClsMatch(nd, std.ascii.toUpper(ch)) else _rClsMatch(nd, ch),
                else => false,
            };
            if (ok) _re_eclosure_s(re, &nxt, vis, alloc, nd.out1, t.saves, pos + 1, input) catch {};
        }
        std.mem.swap(std.ArrayListUnmanaged(_RegThread), &cur, &nxt);
        for (cur.items) |t| { if (re.nodes[t.state].kind == .match) { last = t.saves; if (re.flags.lazy_match) return last; break; } }
    }
    return last;
}
fn _regex_groups(re: Regex, input: []const u8) []const []const u8 {
    const alloc = std.heap.page_allocator;
    var start: usize = 0;
    while (start <= input.len) : (start += 1) {
        if (_re_match_with_saves(&re, input, start)) |saves| {
            var out: std.ArrayListUnmanaged([]const u8) = .{};
            var i: usize = 0;
            while (i + 1 < _MAX_SAVE_SLOTS) : (i += 2) {
                const s = saves[i]; const e = saves[i + 1];
                if (s == 0xFFFF_FFFF_FFFF_FFFF) break;
                if (e != 0xFFFF_FFFF_FFFF_FFFF and e >= s) out.append(alloc, input[s..e]) catch {};
            }
            return out.toOwnedSlice(alloc) catch &.{};
        }
    }
    return &.{};
}
// ─── GUI: backend isolation ──────────────────────────────────────────────────
// _GuiBackend is an fn-ptr struct.  Swap `_gui_active_backend` to change
// the renderer without touching user code or GuiContext.
const _GuiBackend = struct {
    initFn:        *const fn (title: []const u8, width: i64, height: i64) anyerror!void,
    deinitFn:      *const fn () void,
    newFrameFn:    *const fn () bool,
    endFrameFn:    *const fn () void,
    textFn:        *const fn (s: []const u8) void,
    separatorFn:   *const fn () void,
    sameLineFn:    *const fn () void,
    spacingFn:     *const fn () void,
    indentFn:      *const fn () void,
    unindentFn:    *const fn () void,
    buttonFn:      *const fn (label: []const u8) bool,
    checkboxFn:    *const fn (label: []const u8, value: bool) bool,
    sliderFn:      *const fn (label: []const u8, value: f64, min: f64, max: f64) f64,
    inputFn:       *const fn (label: []const u8, value: []const u8) []const u8,
    inputMultilineFn: *const fn (label: []const u8, value: []const u8, width: f64, height: f64) []const u8,
    beginPanelFn:  *const fn (label: []const u8) bool,
    endPanelFn:    *const fn () void,
    beginWindowFn: *const fn (label: []const u8) bool,
    endWindowFn:   *const fn () void,
};
const GuiContext = struct {
    _b: *const _GuiBackend,
    pub fn text(self: GuiContext, s: []const u8) void { self._b.textFn(s); }
    pub fn separator(self: GuiContext) void { self._b.separatorFn(); }
    pub fn sameLine(self: GuiContext) void { self._b.sameLineFn(); }
    pub fn spacing(self: GuiContext) void { self._b.spacingFn(); }
    pub fn indent(self: GuiContext) void { self._b.indentFn(); }
    pub fn unindent(self: GuiContext) void { self._b.unindentFn(); }
    pub fn button(self: GuiContext, label: []const u8) bool { return self._b.buttonFn(label); }
    pub fn checkbox(self: GuiContext, label: []const u8, value: bool) bool { return self._b.checkboxFn(label, value); }
    pub fn slider(self: GuiContext, label: []const u8, value: f64, min: f64, max: f64) f64 { return self._b.sliderFn(label, value, min, max); }
    pub fn input(self: GuiContext, label: []const u8, value: []const u8) []const u8 { return self._b.inputFn(label, value); }
    pub fn inputMultiline(self: GuiContext, label: []const u8, value: []const u8, width: f64, height: f64) []const u8 { return self._b.inputMultilineFn(label, value, width, height); }
    pub fn panel(self: GuiContext, label: []const u8, callback: anytype) void {
        if (self._b.beginPanelFn(label)) {
            if (comptime @typeInfo(@TypeOf(callback)) == .@"fn") callback(self) else callback.call(self);
            self._b.endPanelFn();
        }
    }
    pub fn window(self: GuiContext, label: []const u8, callback: anytype) void {
        if (self._b.beginWindowFn(label)) {
            if (comptime @typeInfo(@TypeOf(callback)) == .@"fn") callback(self) else callback.call(self);
            self._b.endWindowFn();
        }
    }
};
fn _gui_run(title: []const u8, width: i64, height: i64, frame: anytype) void {
    _gui_active_backend.initFn(title, width, height) catch @panic("gui init failed");
    defer _gui_active_backend.deinitFn();
    const _g = GuiContext{ ._b = &_gui_active_backend };
    if (comptime @typeInfo(@TypeOf(frame)) == .@"fn") {
        while (_gui_active_backend.newFrameFn()) {
            frame(_g);
            _gui_active_backend.endFrameFn();
        }
    } else {
        var _mframe = frame;
        while (_gui_active_backend.newFrameFn()) {
            _mframe.call(_g);
            _gui_active_backend.endFrameFn();
        }
    }
}
// ─── Stub backend (single frame, prints to stderr) ───────────────────────────
fn _stub_init(title: []const u8, width: i64, height: i64) anyerror!void {
    _ = title; _ = width; _ = height;
}
fn _stub_deinit() void {}
var _stub_frame_count: u8 = 0;
fn _stub_new_frame() bool {
    if (_stub_frame_count >= 1) return false;
    _stub_frame_count += 1;
    return true;
}
fn _stub_end_frame() void {}
fn _stub_text(s: []const u8) void { std.debug.print("[gui] text: {s}\n", .{s}); }
fn _stub_separator() void { std.debug.print("[gui] ---\n", .{}); }
fn _stub_same_line() void { std.debug.print("[gui] sameLine\n", .{}); }
fn _stub_spacing() void { std.debug.print("[gui] spacing\n", .{}); }
fn _stub_indent() void { std.debug.print("[gui] indent\n", .{}); }
fn _stub_unindent() void { std.debug.print("[gui] unindent\n", .{}); }
fn _stub_button(label: []const u8) bool {
    std.debug.print("[gui] button: {s}\n", .{label});
    return false;
}
fn _stub_checkbox(label: []const u8, value: bool) bool {
    std.debug.print("[gui] checkbox: {s} = {}\n", .{ label, value });
    return value;
}
fn _stub_slider(label: []const u8, value: f64, min: f64, max: f64) f64 {
    std.debug.print("[gui] slider: {s} = {d} [{d}, {d}]\n", .{ label, value, min, max });
    return value;
}
fn _stub_input(label: []const u8, value: []const u8) []const u8 {
    std.debug.print("[gui] input: {s} = {s}\n", .{ label, value });
    return value;
}
fn _stub_input_multiline(label: []const u8, value: []const u8, width: f64, height: f64) []const u8 {
    std.debug.print("[gui] inputMultiline: {s} ({d}x{d})\n", .{ label, width, height });
    return value;
}
fn _stub_begin_panel(label: []const u8) bool {
    std.debug.print("[gui] panel: {s}\n", .{label});
    return true;
}
fn _stub_end_panel() void {}
fn _stub_begin_window(label: []const u8) bool {
    std.debug.print("[gui] window: {s}\n", .{label});
    return true;
}
fn _stub_end_window() void {}
const _gui_stub_backend = _GuiBackend{
    .initFn        = _stub_init,
    .deinitFn      = _stub_deinit,
    .newFrameFn    = _stub_new_frame,
    .endFrameFn    = _stub_end_frame,
    .textFn        = _stub_text,
    .separatorFn   = _stub_separator,
    .sameLineFn    = _stub_same_line,
    .spacingFn     = _stub_spacing,
    .indentFn      = _stub_indent,
    .unindentFn    = _stub_unindent,
    .buttonFn      = _stub_button,
    .checkboxFn    = _stub_checkbox,
    .sliderFn      = _stub_slider,
    .inputFn       = _stub_input,
    .inputMultilineFn = _stub_input_multiline,
    .beginPanelFn  = _stub_begin_panel,
    .endPanelFn    = _stub_end_panel,
    .beginWindowFn = _stub_begin_window,
    .endWindowFn   = _stub_end_window,
};
const _gui_active_backend: _GuiBackend = _gui_stub_backend;
fn _hex_encode(bytes: []const u8) []const u8 {
    const _hx = "0123456789abcdef";
    var out = _allocator.alloc(u8, bytes.len * 2) catch return "";
    for (bytes, 0..) |b, i| { out[i*2] = _hx[b >> 4]; out[i*2+1] = _hx[b & 0xf]; }
    return out;
}
fn _hash_sha256(data: []const u8) []const u8 {
    var out: [std.crypto.hash.sha2.Sha256.digest_length]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(data, &out, .{});
    return _hex_encode(&out);
}
fn _hash_sha512(data: []const u8) []const u8 {
    var out: [std.crypto.hash.sha2.Sha512.digest_length]u8 = undefined;
    std.crypto.hash.sha2.Sha512.hash(data, &out, .{});
    return _hex_encode(&out);
}
fn _hash_md5(data: []const u8) []const u8 {
    var out: [std.crypto.hash.Md5.digest_length]u8 = undefined;
    std.crypto.hash.Md5.hash(data, &out, .{});
    return _hex_encode(&out);
}
fn _hash_blake3(data: []const u8) []const u8 {
    var out: [std.crypto.hash.Blake3.digest_length]u8 = undefined;
    std.crypto.hash.Blake3.hash(data, &out, .{});
    return _hex_encode(&out);
}
fn _hash_hmac256(key: []const u8, data: []const u8) []const u8 {
    var out: [std.crypto.auth.hmac.sha2.HmacSha256.mac_length]u8 = undefined;
    std.crypto.auth.hmac.sha2.HmacSha256.create(&out, data, key);
    return _hex_encode(&out);
}
var _rng_inst: std.Random.DefaultPrng = undefined;
var _rng_ready: bool = false;
fn _rng() std.Random {
    if (!_rng_ready) {
        var seed: u64 = 0;
        std.crypto.random.bytes(std.mem.asBytes(&seed));
        _rng_inst = std.Random.DefaultPrng.init(seed);
        _rng_ready = true;
    }
    return _rng_inst.random();
}
fn _random_int(mn: i64, mx: i64) i64 { return _rng().intRangeAtMost(i64, mn, mx); }
fn _random_float() f64               { return _rng().float(f64); }
fn _random_bool() bool               { return _rng().boolean(); }
fn _random_bytes(n: i64) []const u8 {
    const len: usize = @intCast(if (n < 0) 0 else n);
    const buf = _allocator.alloc(u8, len) catch return "";
    _rng().bytes(buf);
    return _hex_encode(buf);
}
fn _random_seed(s: i64) void {
    _rng_inst = std.Random.DefaultPrng.init(@bitCast(s));
    _rng_ready = true;
}
const ArgResult = struct {
    _raw: []const []const u8,
    pub fn flag(self: ArgResult, long: []const u8, short: []const u8) bool {
        for (self._raw) |a| { if (std.mem.eql(u8, a, long)) return true; if (std.mem.eql(u8, a, short)) return true; }
        return false;
    }
    pub fn contains(self: ArgResult, name_: []const u8) bool {
        for (self._raw) |a| { if (std.mem.eql(u8, a, name_)) return true; }
        return false;
    }
    pub fn option(self: ArgResult, name_: []const u8, default_val: []const u8) []const u8 {
        var i: usize = 0;
        while (i + 1 < self._raw.len) : (i += 1) {
            if (std.mem.eql(u8, self._raw[i], name_)) return self._raw[i + 1];
        }
        return default_val;
    }
    pub fn optionInt(self: ArgResult, name_: []const u8, default_val: i64) i64 {
        const s = self.option(name_, "");
        if (s.len == 0) return default_val;
        return std.fmt.parseInt(i64, s, 10) catch default_val;
    }
    pub fn positional(self: ArgResult, idx: i64) ?[]const u8 {
        var pos: usize = 0;
        for (self._raw) |a| {
            if (!std.mem.startsWith(u8, a, "-")) {
                if (pos == @as(usize, @intCast(idx))) return a;
                pos += 1;
            }
        }
        return null;
    }
    pub fn usage(_: ArgResult) []const u8 { return "Usage: program [options]"; }
};
fn _arg_parse() ArgResult {
    const _argv = std.process.argsAlloc(_allocator) catch return ArgResult{ ._raw = &.{} };
    const _raw_slice = if (_argv.len > 1) _argv[1..] else _argv[0..0];
    var _out = _allocator.alloc([]const u8, _raw_slice.len) catch return ArgResult{ ._raw = &.{} };
    for (_raw_slice, 0..) |a, i| _out[i] = a;
    return ArgResult{ ._raw = _out };
}
fn _term_is_tty() bool {
    const cfg = std.io.tty.detectConfig(std.fs.File.stdout());
    return cfg != .no_color;
}
fn _term_width() i64 { return 80; }
fn _term_height() i64 { return 24; }
fn _term_ansi(color: []const u8) []const u8 {
    if (std.mem.eql(u8, color, "red"))     return "\x1b[31m";
    if (std.mem.eql(u8, color, "green"))   return "\x1b[32m";
    if (std.mem.eql(u8, color, "yellow"))  return "\x1b[33m";
    if (std.mem.eql(u8, color, "blue"))    return "\x1b[34m";
    if (std.mem.eql(u8, color, "magenta")) return "\x1b[35m";
    if (std.mem.eql(u8, color, "cyan"))    return "\x1b[36m";
    if (std.mem.eql(u8, color, "white"))   return "\x1b[37m";
    if (std.mem.eql(u8, color, "dim"))     return "\x1b[2m";
    if (std.mem.eql(u8, color, "bold"))    return "\x1b[1m";
    return "";
}
fn _term_print(msg: []const u8, color: []const u8, newline: bool) void {
    const _f = std.fs.File.stdout();
    if (_term_is_tty() and color.len > 0) {
        _f.deprecatedWriter().print("{s}{s}\x1b[0m", .{ _term_ansi(color), msg }) catch {};
    } else {
        _f.deprecatedWriter().writeAll(msg) catch {};
    }
    if (newline) _f.deprecatedWriter().writeByte('\n') catch {};
}
var _log_level: u8 = 1;        // default: info
var _log_timestamps: bool = true;
var _log_to_stderr: bool = true;
fn _log_ts() []const u8 {
    const sec = @divFloor(std.time.milliTimestamp(), 1000);
    const s = sec - 62135596800; // offset from Unix epoch to .NET epoch (unused here)
    _ = s;
    return std.fmt.allocPrint(_allocator, "{d}", .{sec}) catch "?";
}
fn _log_emit(level_str: []const u8, level_num: u8, msg: []const u8) void {
    if (level_num < _log_level) return;
    const _lw = if (_log_to_stderr) std.fs.File.stderr().deprecatedWriter() else std.fs.File.stdout().deprecatedWriter();
    if (_log_timestamps) {
        _lw.print("[{s:<5} {s}] {s}\n", .{ level_str, _log_ts(), msg }) catch {};
    } else {
        _lw.print("[{s:<5}] {s}\n", .{ level_str, msg }) catch {};
    }
}
fn _log_debug(msg: []const u8) void { _log_emit("DEBUG", 0, msg); }
fn _log_info(msg: []const u8) void  { _log_emit("INFO",  1, msg); }
fn _log_warn(msg: []const u8) void  { _log_emit("WARN",  2, msg); }
fn _log_err(msg: []const u8) void   { _log_emit("ERR",   3, msg); }
fn _log_set_level(l: u8) void { _log_level = l; }
fn _log_set_output_stderr(v: bool) void { _log_to_stderr = v; }
fn _log_timestamp(v: bool) void { _log_timestamps = v; }
const UriResult = struct {
    scheme: []const u8,
    host:   []const u8,
    path:   []const u8,
    query:  []const u8,
    port:   i64,
};
fn _uri_parse(url: []const u8) UriResult {
    const _u = std.Uri.parse(url) catch return UriResult{ .scheme="", .host="", .path="", .query="", .port=0 };
    const _host: []const u8 = if (_u.host) |h| switch (h) {
        .raw => |r| r, .percent_encoded => |p| p,
    } else "";
    const _path: []const u8 = switch (_u.path) {
        .raw => |r| r, .percent_encoded => |p| p,
    };
    const _query: []const u8 = if (_u.query) |q| switch (q) {
        .raw => |r| r, .percent_encoded => |p| p,
    } else "";
    return UriResult{
        .scheme = _u.scheme,
        .host   = _host,
        .path   = _path,
        .query  = _query,
        .port   = if (_u.port) |p| @intCast(p) else 0,
    };
}
fn _compress_gzip(_: []const u8) []const u8 { return ""; }
fn _compress_gunzip(data: []const u8) ?[]const u8 {
    var _in = std.Io.Reader.fixed(data);
    var _window: [std.compress.flate.max_window_len]u8 = undefined;
    var _decomp = std.compress.flate.Decompress.init(&_in, .gzip, &_window);
    return _decomp.reader.allocRemaining(_allocator, .unlimited) catch null;
}
fn _mime_from_ext(ext: []const u8) []const u8 {
    const _map = [_]struct { []const u8, []const u8 }{
        .{ ".html",  "text/html" },          .{ ".htm",   "text/html" },
        .{ ".css",   "text/css" },
        .{ ".js",    "text/javascript" },    .{ ".mjs",   "text/javascript" },
        .{ ".ts",    "text/typescript" },
        .{ ".json",  "application/json" },
        .{ ".xml",   "application/xml" },
        .{ ".txt",   "text/plain" },
        .{ ".csv",   "text/csv" },
        .{ ".md",    "text/markdown" },
        .{ ".png",   "image/png" },
        .{ ".jpg",   "image/jpeg" },         .{ ".jpeg",  "image/jpeg" },
        .{ ".gif",   "image/gif" },
        .{ ".svg",   "image/svg+xml" },
        .{ ".ico",   "image/x-icon" },
        .{ ".webp",  "image/webp" },
        .{ ".pdf",   "application/pdf" },
        .{ ".zip",   "application/zip" },
        .{ ".gz",    "application/gzip" },
        .{ ".tar",   "application/x-tar" },
        .{ ".mp3",   "audio/mpeg" },
        .{ ".mp4",   "video/mp4" },
        .{ ".wav",   "audio/wav" },
        .{ ".ogg",   "audio/ogg" },
        .{ ".webm",  "video/webm" },
        .{ ".wasm",  "application/wasm" },
        .{ ".ttf",   "font/ttf" },
        .{ ".woff",  "font/woff" },
        .{ ".woff2", "font/woff2" },
    };
    for (_map) |e| if (std.mem.eql(u8, e[0], ext)) return e[1];
    return "application/octet-stream";
}
fn _mime_to_ext(mime: []const u8) []const u8 {
    const _map = [_]struct { []const u8, []const u8 }{
        .{ "text/html",        ".html" },
        .{ "text/css",         ".css"  },
        .{ "text/javascript",  ".js"   },
        .{ "text/plain",       ".txt"  },
        .{ "text/csv",         ".csv"  },
        .{ "text/markdown",    ".md"   },
        .{ "application/json", ".json" },
        .{ "application/xml",  ".xml"  },
        .{ "application/pdf",  ".pdf"  },
        .{ "application/zip",  ".zip"  },
        .{ "application/gzip", ".gz"   },
        .{ "application/wasm", ".wasm" },
        .{ "image/png",        ".png"  },
        .{ "image/jpeg",       ".jpg"  },
        .{ "image/gif",        ".gif"  },
        .{ "image/svg+xml",    ".svg"  },
        .{ "image/webp",       ".webp" },
        .{ "audio/mpeg",       ".mp3"  },
        .{ "audio/wav",        ".wav"  },
        .{ "video/mp4",        ".mp4"  },
    };
    for (_map) |e| if (std.mem.eql(u8, e[0], mime)) return e[1];
    return "";
}
const TimerHandle = struct {
    _start_ns: i128,
    pub fn elapsed(self: *const TimerHandle) f64 {
        const _ns: i128 = std.time.nanoTimestamp() - self._start_ns;
        return @as(f64, @floatFromInt(_ns)) / 1_000_000.0;
    }
    pub fn elapsedMicros(self: *const TimerHandle) i64 {
        const _ns: i128 = std.time.nanoTimestamp() - self._start_ns;
        return @intCast(@divFloor(_ns, 1000));
    }
    pub fn reset(self: *TimerHandle) void {
        self._start_ns = std.time.nanoTimestamp();
    }
};
fn _timer_start() TimerHandle { return .{ ._start_ns = std.time.nanoTimestamp() }; }
pub const Type = union(enum) {
    unknown,
    int_,
    float_,
    bool_,
    char_,
    str_,
    void_,
    uint_,
    int_n: i64,
    uint_n: i64,
    optional: *Type,
    error_union: *Type,
    list_: *Type,
    named: []const u8,
    tuple: std.ArrayList(Type),
    cross_module: CrossModuleRef,
    string_builder,
    http_response,
    regex,
    gui_context,
};

pub const CrossModuleRef = struct {
    module: []const u8 = undefined,
    type_name: []const u8 = undefined,
    pub fn init(mod: []const u8, tname: []const u8) CrossModuleRef {
        var self: CrossModuleRef = undefined;
// zbr:test/selfhost_probe5.zbr:51
        self.module = mod;
// zbr:test/selfhost_probe5.zbr:52
        self.type_name = tname;
        return self;
    }

};

pub const Types = struct {
    _type_tag: u64 = _ttag_Types,
    pub fn describe(t: Type) []const u8 {
// zbr:test/selfhost_probe5.zbr:61
        switch (t) {
            .unknown => {
// zbr:test/selfhost_probe5.zbr:62
                return "unknown";
            },
            .int_ => {
// zbr:test/selfhost_probe5.zbr:63
                return "int";
            },
            .float_ => {
// zbr:test/selfhost_probe5.zbr:64
                return "float";
            },
            .bool_ => {
// zbr:test/selfhost_probe5.zbr:65
                return "bool";
            },
            .char_ => {
// zbr:test/selfhost_probe5.zbr:66
                return "char";
            },
            .str_ => {
// zbr:test/selfhost_probe5.zbr:67
                return "str";
            },
            .void_ => {
// zbr:test/selfhost_probe5.zbr:68
                return "void";
            },
            .uint_ => {
// zbr:test/selfhost_probe5.zbr:69
                return "uint";
            },
            .int_n => |bits| {
// zbr:test/selfhost_probe5.zbr:71
                return _str_concat("int", (std.fmt.allocPrint(_allocator, "{}", .{bits}) catch unreachable), _allocator);
            },
            .uint_n => |bits| {
// zbr:test/selfhost_probe5.zbr:73
                return _str_concat("uint", (std.fmt.allocPrint(_allocator, "{}", .{bits}) catch unreachable), _allocator);
            },
            .optional => |inner_ptr| {
                const inner = inner_ptr.*;
// zbr:test/selfhost_probe5.zbr:76
                return _str_concat("?", Types.describe(inner), _allocator);
            },
            .error_union => |inner_ptr| {
                const inner = inner_ptr.*;
// zbr:test/selfhost_probe5.zbr:78
                return _str_concat("!", Types.describe(inner), _allocator);
            },
            .list_ => |elem_ptr| {
                const elem = elem_ptr.*;
// zbr:test/selfhost_probe5.zbr:80
                return _str_concat(_str_concat("List(", Types.describe(elem), _allocator), ")", _allocator);
            },
            .named => |n| {
// zbr:test/selfhost_probe5.zbr:82
                return n;
            },
            .tuple => |elems| {
// zbr:test/selfhost_probe5.zbr:84
                var parts: []const u8 = "";
// zbr:test/selfhost_probe5.zbr:85
                var first: bool = true;
// zbr:test/selfhost_probe5.zbr:86
                for (elems.items) |e| {
// zbr:test/selfhost_probe5.zbr:87
                    if ((!first)) {
// zbr:test/selfhost_probe5.zbr:88
                        parts = _str_concat(parts, ", ", _allocator);
                    }
// zbr:test/selfhost_probe5.zbr:89
                    parts = _str_concat(parts, Types.describe(e), _allocator);
// zbr:test/selfhost_probe5.zbr:90
                    first = false;
                }
// zbr:test/selfhost_probe5.zbr:91
                return _str_concat(_str_concat("(", parts, _allocator), ")", _allocator);
            },
            .cross_module => |ref| {
// zbr:test/selfhost_probe5.zbr:93
                return _str_concat(_str_concat(ref.module, ".", _allocator), ref.type_name, _allocator);
            },
            .string_builder => {
// zbr:test/selfhost_probe5.zbr:94
                return "StringBuilder";
            },
            .http_response => {
// zbr:test/selfhost_probe5.zbr:95
                return "HttpResponse";
            },
            .regex => {
// zbr:test/selfhost_probe5.zbr:96
                return "Regex";
            },
            .gui_context => {
// zbr:test/selfhost_probe5.zbr:97
                return "Gui";
            },
        }
    }

    pub fn eql(_p_a: Type, _p_b: Type) bool {
        var a = _p_a;
        var b = _p_b;
        while (true) {
// zbr:test/selfhost_probe5.zbr:102
            switch (a) {
                .int_ => {
// zbr:test/selfhost_probe5.zbr:103
                    return std.meta.eql(b, Type{ .int_ = {} });
                },
                .str_ => {
// zbr:test/selfhost_probe5.zbr:104
                    return std.meta.eql(b, Type{ .str_ = {} });
                },
                .bool_ => {
// zbr:test/selfhost_probe5.zbr:105
                    return std.meta.eql(b, Type{ .bool_ = {} });
                },
                .optional => |ia_ptr| {
                    const ia = ia_ptr.*;
// zbr:test/selfhost_probe5.zbr:107
                    switch (b) {
                        .optional => |ib_ptr| {
                            const ib = ib_ptr.*;
// zbr:test/selfhost_probe5.zbr:109
                            { const _tco0 = ia; const _tco1 = ib; a = _tco0; b = _tco1; }
                            continue;
                        },
                        else => {
// zbr:test/selfhost_probe5.zbr:111
                            return false;
                        },
                    }
                },
                .list_ => |ea_ptr| {
                    const ea = ea_ptr.*;
// zbr:test/selfhost_probe5.zbr:113
                    switch (b) {
                        .list_ => |eb_ptr| {
                            const eb = eb_ptr.*;
// zbr:test/selfhost_probe5.zbr:115
                            { const _tco0 = ea; const _tco1 = eb; a = _tco0; b = _tco1; }
                            continue;
                        },
                        else => {
// zbr:test/selfhost_probe5.zbr:117
                            return false;
                        },
                    }
                },
                .named => |na| {
// zbr:test/selfhost_probe5.zbr:119
                    switch (b) {
                        .named => |nb| {
// zbr:test/selfhost_probe5.zbr:121
                            return std.mem.eql(u8, na, nb);
                        },
                        else => {
// zbr:test/selfhost_probe5.zbr:123
                            return false;
                        },
                    }
                },
                else => {
// zbr:test/selfhost_probe5.zbr:125
                    return false;
                },
            }
        }
    }

    pub fn init() Types {
        var self: Types = undefined;
        self._type_tag = _ttag_Types;
        return self;
    }

};

const _ttag_Types: u64 = 2820054842;
const _reflect_Types_name: []const u8 = "Types";
const _reflect_Types_fields: []const []const u8 = &.{};
const _reflect_Types_field_types: []const []const u8 = &.{};

pub const TypeEnv = struct {
    _type_tag: u64 = _ttag_TypeEnv,
    types: std.StringHashMap(Type) = undefined,
    pub fn init() TypeEnv {
        var self: TypeEnv = undefined;
        self._type_tag = _ttag_TypeEnv;
// zbr:test/selfhost_probe5.zbr:133
        self.types = std.StringHashMap(Type).init(_allocator);
        return self;
    }

    pub fn define(self: *TypeEnv, name: []const u8, t: Type) void {
// zbr:test/selfhost_probe5.zbr:136
        self.types.put((_allocator.dupe(u8, name) catch @panic("OOM")), t) catch unreachable;
    }

    pub fn lookup(self: *TypeEnv, name: []const u8) Type {
// zbr:test/selfhost_probe5.zbr:139
        if (self.types.contains(name)) {
// zbr:test/selfhost_probe5.zbr:140
            return (self.types.get(name) orelse undefined);
        }
// zbr:test/selfhost_probe5.zbr:141
        return Type{ .unknown = {} };
    }

    pub fn contains(self: *TypeEnv, name: []const u8) bool {
// zbr:test/selfhost_probe5.zbr:144
        return self.types.contains(name);
    }

};

const _ttag_TypeEnv: u64 = 2913822268;
const _reflect_TypeEnv_name: []const u8 = "TypeEnv";
const _reflect_TypeEnv_fields: []const []const u8 = &.{"types"};
const _reflect_TypeEnv_field_types: []const []const u8 = &.{"HashMap(str, Type)"};

pub const Expr = union(enum) {
    int_lit: i64,
    str_lit: []const u8,
    neg: *Expr,
    add: ExprPair,
};

pub const ExprPair = struct {
    left: *Expr = undefined,
    right: *Expr = undefined,
    pub fn init(l: Expr, r: Expr) ExprPair {
        var self: ExprPair = undefined;
// zbr:test/selfhost_probe5.zbr:159
        { const _rp = _allocator.create(Expr) catch @panic("OOM"); _rp.* = l; self.left = _rp; }
// zbr:test/selfhost_probe5.zbr:160
        { const _rp = _allocator.create(Expr) catch @panic("OOM"); _rp.* = r; self.right = _rp; }
        return self;
    }

};

pub const Checker = struct {
    _type_tag: u64 = _ttag_Checker,
    errors: std.ArrayList([]const u8) = undefined,
    pub fn init() Checker {
        var self: Checker = undefined;
        self._type_tag = _ttag_Checker;
// zbr:test/selfhost_probe5.zbr:165
        self.errors = std.ArrayList([]const u8){};
        return self;
    }

    pub fn inferExpr(self: *Checker, e: Expr) anyerror!Type {
// zbr:test/selfhost_probe5.zbr:168
        switch (e) {
            .int_lit => {
// zbr:test/selfhost_probe5.zbr:170
                return Type{ .int_ = {} };
            },
            .str_lit => {
// zbr:test/selfhost_probe5.zbr:172
                return Type{ .str_ = {} };
            },
            .neg => |inner_ptr| {
                const inner = inner_ptr.*;
// zbr:test/selfhost_probe5.zbr:174
                const t = try self.inferExpr(inner);
// zbr:test/selfhost_probe5.zbr:175
                if ((!std.meta.eql(t, Type{ .int_ = {} }) and !std.meta.eql(t, Type{ .float_ = {} }))) {
// zbr:test/selfhost_probe5.zbr:176
                    _error_ctx = .{ .message = "neg requires numeric type", .details = null };
                    return error.ZebraError;
                }
// zbr:test/selfhost_probe5.zbr:177
                return t;
            },
            .add => |pair| {
// zbr:test/selfhost_probe5.zbr:179
                const lt = try self.inferExpr(pair.left.*);
// zbr:test/selfhost_probe5.zbr:180
                const rt = try self.inferExpr(pair.right.*);
// zbr:test/selfhost_probe5.zbr:181
                if (!std.meta.eql(lt, Type{ .int_ = {} })) {
// zbr:test/selfhost_probe5.zbr:182
                    _error_ctx = .{ .message = "add requires int left", .details = null };
                    return error.ZebraError;
                }
// zbr:test/selfhost_probe5.zbr:183
                if (!std.meta.eql(rt, Type{ .int_ = {} })) {
// zbr:test/selfhost_probe5.zbr:184
                    _error_ctx = .{ .message = "add requires int right", .details = null };
                    return error.ZebraError;
                }
// zbr:test/selfhost_probe5.zbr:185
                return Type{ .int_ = {} };
            },
        }
    }

    pub fn checkExpr(self: *Checker, e: Expr, expected: Type) anyerror!void {
// zbr:test/selfhost_probe5.zbr:188
        const actual = try self.inferExpr(e);
// zbr:test/selfhost_probe5.zbr:189
        if ((!Types.eql(actual, expected))) {
// zbr:test/selfhost_probe5.zbr:190
            _error_ctx = .{ .message = "type mismatch", .details = null };
            return error.ZebraError;
        }
    }

};

const _ttag_Checker: u64 = 1673152188;
const _reflect_Checker_name: []const u8 = "Checker";
const _reflect_Checker_fields: []const []const u8 = &.{"errors"};
const _reflect_Checker_field_types: []const []const u8 = &.{"List(str)"};

pub const Main = struct {
    _type_tag: u64 = _ttag_Main,
    pub fn main() anyerror!void {
// zbr:test/selfhost_probe5.zbr:198
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .int_ = {} }), "int"));
// zbr:test/selfhost_probe5.zbr:199
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .str_ = {} }), "str"));
// zbr:test/selfhost_probe5.zbr:200
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .unknown = {} }), "unknown"));
// zbr:test/selfhost_probe5.zbr:201
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .void_ = {} }), "void"));
// zbr:test/selfhost_probe5.zbr:202
        std.debug.print("{s}\n", .{"1. unit variants OK"});
// zbr:test/selfhost_probe5.zbr:205
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .int_n = 32 }), "int32"));
// zbr:test/selfhost_probe5.zbr:206
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .uint_n = 64 }), "uint64"));
// zbr:test/selfhost_probe5.zbr:207
        std.debug.assert(std.mem.eql(u8, Types.describe(Type{ .named = "Point" }), "Point"));
// zbr:test/selfhost_probe5.zbr:208
        std.debug.print("{s}\n", .{"2. payload variants OK"});
// zbr:test/selfhost_probe5.zbr:211
        const opt_int = Type{ .optional = _box_15aed524b38: { const _bp_15aed524b38 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed524b38.* = Type{ .int_ = {} }; break :_box_15aed524b38 _bp_15aed524b38; } };
// zbr:test/selfhost_probe5.zbr:212
        const list_str = Type{ .list_ = _box_15aed524d78: { const _bp_15aed524d78 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed524d78.* = Type{ .str_ = {} }; break :_box_15aed524d78 _bp_15aed524d78; } };
// zbr:test/selfhost_probe5.zbr:213
        std.debug.assert(std.mem.eql(u8, Types.describe(opt_int), "?int"));
// zbr:test/selfhost_probe5.zbr:214
        std.debug.assert(std.mem.eql(u8, Types.describe(list_str), "List(str)"));
// zbr:test/selfhost_probe5.zbr:215
        std.debug.print("{s}\n", .{"3. recursive ^T OK"});
// zbr:test/selfhost_probe5.zbr:218
        const opt_list = Type{ .optional = _box_15aed525478: { const _bp_15aed525478 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed525478.* = Type{ .list_ = _box_15aed5253f0: { const _bp_15aed5253f0 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed5253f0.* = Type{ .str_ = {} }; break :_box_15aed5253f0 _bp_15aed5253f0; } }; break :_box_15aed525478 _bp_15aed525478; } };
// zbr:test/selfhost_probe5.zbr:219
        const list_opt = Type{ .list_ = _box_15aed5257b8: { const _bp_15aed5257b8 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed5257b8.* = Type{ .optional = _box_15aed525730: { const _bp_15aed525730 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed525730.* = Type{ .int_ = {} }; break :_box_15aed525730 _bp_15aed525730; } }; break :_box_15aed5257b8 _bp_15aed5257b8; } };
// zbr:test/selfhost_probe5.zbr:220
        std.debug.assert(std.mem.eql(u8, Types.describe(opt_list), "?List(str)"));
// zbr:test/selfhost_probe5.zbr:221
        std.debug.assert(std.mem.eql(u8, Types.describe(list_opt), "List(?int)"));
// zbr:test/selfhost_probe5.zbr:222
        std.debug.print("{s}\n", .{"4. doubly nested OK"});
// zbr:test/selfhost_probe5.zbr:225
        var elems = std.ArrayList(Type){};
// zbr:test/selfhost_probe5.zbr:226
        elems.append(_allocator, Type{ .int_ = {} }) catch unreachable;
// zbr:test/selfhost_probe5.zbr:227
        elems.append(_allocator, Type{ .str_ = {} }) catch unreachable;
// zbr:test/selfhost_probe5.zbr:228
        const tup = Type{ .tuple = elems };
// zbr:test/selfhost_probe5.zbr:229
        std.debug.assert(std.mem.eql(u8, Types.describe(tup), "(int, str)"));
// zbr:test/selfhost_probe5.zbr:230
        std.debug.print("{s}\n", .{"5. tuple (List inside union) OK"});
// zbr:test/selfhost_probe5.zbr:233
        const xmod = Type{ .cross_module = CrossModuleRef.init("math", "Vector") };
// zbr:test/selfhost_probe5.zbr:234
        std.debug.assert(std.mem.eql(u8, Types.describe(xmod), "math.Vector"));
// zbr:test/selfhost_probe5.zbr:235
        std.debug.print("{s}\n", .{"6. cross_module struct payload OK"});
// zbr:test/selfhost_probe5.zbr:238
        var env = TypeEnv.init();
// zbr:test/selfhost_probe5.zbr:239
        env.define("x", Type{ .int_ = {} });
// zbr:test/selfhost_probe5.zbr:240
        env.define("y", Type{ .optional = _box_15aed620200: { const _bp_15aed620200 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed620200.* = Type{ .str_ = {} }; break :_box_15aed620200 _bp_15aed620200; } });
// zbr:test/selfhost_probe5.zbr:241
        env.define("z", Type{ .list_ = _box_15aed620550: { const _bp_15aed620550 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed620550.* = Type{ .int_ = {} }; break :_box_15aed620550 _bp_15aed620550; } });
// zbr:test/selfhost_probe5.zbr:242
        std.debug.assert(std.mem.eql(u8, Types.describe(env.lookup("x")), "int"));
// zbr:test/selfhost_probe5.zbr:243
        std.debug.assert(std.mem.eql(u8, Types.describe(env.lookup("y")), "?str"));
// zbr:test/selfhost_probe5.zbr:244
        std.debug.assert(std.mem.eql(u8, Types.describe(env.lookup("z")), "List(int)"));
// zbr:test/selfhost_probe5.zbr:245
        std.debug.assert(env.contains("x"));
// zbr:test/selfhost_probe5.zbr:246
        std.debug.assert((!env.contains("w")));
// zbr:test/selfhost_probe5.zbr:247
        std.debug.print("{s}\n", .{"7. HashMap(str, Type) OK"});
// zbr:test/selfhost_probe5.zbr:250
        std.debug.assert(Types.eql(Type{ .int_ = {} }, Type{ .int_ = {} }));
// zbr:test/selfhost_probe5.zbr:251
        std.debug.assert((!Types.eql(Type{ .int_ = {} }, Type{ .str_ = {} })));
// zbr:test/selfhost_probe5.zbr:252
        std.debug.assert(Types.eql(Type{ .optional = _box_15aed621dd8: { const _bp_15aed621dd8 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed621dd8.* = Type{ .int_ = {} }; break :_box_15aed621dd8 _bp_15aed621dd8; } }, Type{ .optional = _box_15aed622028: { const _bp_15aed622028 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed622028.* = Type{ .int_ = {} }; break :_box_15aed622028 _bp_15aed622028; } }));
// zbr:test/selfhost_probe5.zbr:253
        std.debug.assert((!Types.eql(Type{ .optional = _box_15aed6222f8: { const _bp_15aed6222f8 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed6222f8.* = Type{ .int_ = {} }; break :_box_15aed6222f8 _bp_15aed6222f8; } }, Type{ .optional = _box_15aed622548: { const _bp_15aed622548 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed622548.* = Type{ .str_ = {} }; break :_box_15aed622548 _bp_15aed622548; } })));
// zbr:test/selfhost_probe5.zbr:254
        std.debug.assert(Types.eql(Type{ .list_ = _box_15aed622858: { const _bp_15aed622858 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed622858.* = Type{ .str_ = {} }; break :_box_15aed622858 _bp_15aed622858; } }, Type{ .list_ = _box_15aed622aa8: { const _bp_15aed622aa8 = _allocator.create(Type) catch @panic("OOM"); _bp_15aed622aa8.* = Type{ .str_ = {} }; break :_box_15aed622aa8 _bp_15aed622aa8; } }));
// zbr:test/selfhost_probe5.zbr:255
        std.debug.print("{s}\n", .{"8. Type.eql OK"});
// zbr:test/selfhost_probe5.zbr:258
        var ch = Checker.init();
// zbr:test/selfhost_probe5.zbr:259
        const lit = Expr{ .int_lit = 42 };
// zbr:test/selfhost_probe5.zbr:260
        const slit = Expr{ .str_lit = "hi" };
// zbr:test/selfhost_probe5.zbr:261
        const neg = Expr{ .neg = _box_15aed6231b0: { const _bp_15aed6231b0 = _allocator.create(Expr) catch @panic("OOM"); _bp_15aed6231b0.* = Expr{ .int_lit = 5 }; break :_box_15aed6231b0 _bp_15aed6231b0; } };
// zbr:test/selfhost_probe5.zbr:262
        const add = Expr{ .add = ExprPair.init(Expr{ .int_lit = 1 }, Expr{ .int_lit = 2 }) };
// zbr:test/selfhost_probe5.zbr:264
        const t1 = try ch.inferExpr(lit);
// zbr:test/selfhost_probe5.zbr:265
        std.debug.assert(Types.eql(t1, Type{ .int_ = {} }));
// zbr:test/selfhost_probe5.zbr:267
        const t2 = try ch.inferExpr(slit);
// zbr:test/selfhost_probe5.zbr:268
        std.debug.assert(Types.eql(t2, Type{ .str_ = {} }));
// zbr:test/selfhost_probe5.zbr:270
        const t3 = try ch.inferExpr(neg);
// zbr:test/selfhost_probe5.zbr:271
        std.debug.assert(Types.eql(t3, Type{ .int_ = {} }));
// zbr:test/selfhost_probe5.zbr:273
        const t4 = try ch.inferExpr(add);
// zbr:test/selfhost_probe5.zbr:274
        std.debug.assert(Types.eql(t4, Type{ .int_ = {} }));
// zbr:test/selfhost_probe5.zbr:276
        try ch.checkExpr(lit, Type{ .int_ = {} });
// zbr:test/selfhost_probe5.zbr:277
        std.debug.print("{s}\n", .{"9. mutual recursion + throws OK"});
// zbr:test/selfhost_probe5.zbr:279
        std.debug.print("{s}\n", .{"selfhost_probe5: all OK"});
    }

    pub fn init() Main {
        var self: Main = undefined;
        self._type_tag = _ttag_Main;
        return self;
    }

};

const _ttag_Main: u64 = 1366325544;
const _reflect_Main_name: []const u8 = "Main";
const _reflect_Main_fields: []const []const u8 = &.{};
const _reflect_Main_field_types: []const []const u8 = &.{};

pub fn main() void {
    _allocator = _arena.allocator();
    defer _arena.deinit();
    Main.main() catch |_err| {
        if (_err == error.ZebraError) {
            std.debug.print("Error: {s}\n", .{_error_ctx.message});
        } else {
            std.debug.print("Error: {}\n", .{_err});
        }
        std.process.exit(1);
    };
}
