// Generated by the Zebra compiler.
// Source: test/throws_raise.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?*anyopaque = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};

pub const App = struct {
    pub fn risky(x: i64) anyerror!i64 {
        if ((x < 0)) {
            _error_ctx = .{ .message = "negative input", .details = @as(*anyopaque, @ptrCast(@constCast(@alignCast(&(x)))))  };
            return error.ZebraError;
        }
        return (x * 2);
    }

    pub fn main() void {
        std.debug.print("{s}\n", .{"throws annotation compiles"});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    App.main();
}
