// Generated by the Zebra compiler.
// Source: test/tostring_test.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

pub const Main = struct {
    pub fn main() void {
        const n: i64 = 42;
        const f: f64 = 3.14;
        const s1 = (std.fmt.allocPrint(_allocator, "{}", .{n}) catch unreachable);
        defer _allocator.free(s1);
        const s2 = (std.fmt.allocPrint(_allocator, "{d}", .{f}) catch unreachable);
        defer _allocator.free(s2);
        std.debug.print("{s}\n", .{s1});
        std.debug.print("{s}\n", .{s2});
        const big: i64 = (-100);
        {
            const _pt0 = (std.fmt.allocPrint(_allocator, "{}", .{big}) catch unreachable);
            defer _allocator.free(_pt0);
            std.debug.print("{s}\n", .{_pt0});
        }
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Main.main();
}
