// Generated by the Zebra compiler.
// Source: test/try_catch_err.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?*anyopaque = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};

pub const App = struct {
    pub fn risky(x: i64) anyerror!i64 {
        if ((x < 0)) {
            _error_ctx = .{ .message = "negative input", .details = @as(*anyopaque, @ptrCast(@constCast(@alignCast(&(x)))))  };
            return error.ZebraError;
        }
        return (x * 2);
    }

    pub fn main() void {
        var _try_err_2948: ?anyerror = null;
        _try_blk_2948: {
            const result: i64 = App.risky((-3)) catch |_tc_1956fab03b8| { _try_err_2948 = _tc_1956fab03b8; break :_try_blk_2948; };
            std.debug.print("{}\n", .{result});
            break :_try_blk_2948;
        }
        if (_try_err_2948 != null) {
            std.debug.print("{s}\n", .{"caught an error"});
        }
        std.debug.print("{s}\n", .{"after try"});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    App.main();
}
