// Generated by the Zebra compiler.
// Source: test/try_outer_vars.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?*anyopaque = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};

pub const App = struct {
    pub fn risky(x: i64) anyerror!i64 {
        if ((x < 0)) {
            _error_ctx = .{ .message = "negative", .details = @as(*anyopaque, @ptrCast(@constCast(@alignCast(&(x)))))  };
            return error.ZebraError;
        }
        return (x * 2);
    }

    pub fn main() void {
        const base: i64 = 10;
        const multiplier: i64 = 3;
        var _try_err_3b0: ?anyerror = null;
        _try_blk_3b0: {
            const result: i64 = App.risky(base) catch |_tc_2d4e2fc0138| { _try_err_3b0 = _tc_2d4e2fc0138; break :_try_blk_3b0; };
            const total: i64 = (result * multiplier);
            std.debug.print("{}\n", .{total});
            break :_try_blk_3b0;
        }
        if (_try_err_3b0 != null) {
            std.debug.print("{s}\n", .{"error"});
        }
        std.debug.print("{}\n", .{base});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    App.main();
}
