// Generated by the Zebra compiler.
// Source: test/udp_test.zbr

const std = @import("std");

var _gpa = std.heap.GeneralPurposeAllocator(.{}){};
const _allocator = _gpa.allocator();

const _Stringable = struct {
    ptr:         *anyopaque,
    toString_fn: *const fn (*anyopaque) []const u8,
    pub fn toString(self: _Stringable) []const u8 {
        return self.toString_fn(self.ptr);
    }
};
const _ZebraErrorCtx = struct { message: []const u8 = "", details: ?_Stringable = null };
threadlocal var _error_ctx: _ZebraErrorCtx = .{};
fn _pad_left(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. width - s.len], fill);
    @memcpy(buf[width - s.len ..], s);
    return buf;
}
fn _pad_right(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memcpy(buf[0 .. s.len], s);
    @memset(buf[s.len ..], fill);
    return buf;
}
fn _pad_center(s: []const u8, width: usize, fill: u8, alloc: std.mem.Allocator) []const u8 {
    if (s.len >= width) return s;
    const pad = width - s.len;
    const lpad = pad / 2;
    const buf = alloc.alloc(u8, width) catch @panic("OOM");
    @memset(buf[0 .. lpad], fill);
    @memcpy(buf[lpad .. lpad + s.len], s);
    @memset(buf[lpad + s.len ..], fill);
    return buf;
}

const HttpResponse = struct { status: u16, text: []const u8 };
fn _http_request(method: std.http.Method, url: []const u8, payload: ?[]const u8) HttpResponse {
    var _hc = std.http.Client{ .allocator = _allocator };
    defer _hc.deinit();
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    const _hr = _hc.fetch(.{ .location = .{ .url = url }, .method = method, .payload = payload, .response_writer = &_hb.writer }) catch |e| @panic(@errorName(e));
    return .{ .status = @intFromEnum(_hr.status), .text = _hb.written() };
}
fn _http_get(url: []const u8) HttpResponse { return _http_request(.GET, url, null); }
fn _http_post(url: []const u8, payload: []const u8) HttpResponse { return _http_request(.POST, url, payload); }

const TcpConn = struct { stream: std.net.Stream };
fn _tcp_connect(host: []const u8, port: u16) TcpConn {
    const s = std.net.tcpConnectToHost(_allocator, host, port) catch |e| @panic(@errorName(e));
    return .{ .stream = s };
}
fn _tcp_write(conn: TcpConn, data: []const u8) void {
    conn.stream.writeAll(data) catch |e| @panic(@errorName(e));
}
fn _tcp_read(conn: TcpConn) []const u8 {
    var _rb: [65536]u8 = undefined;
    var _rd = conn.stream.reader(&_rb);
    var _hb = std.io.Writer.Allocating.init(std.heap.page_allocator);
    _ = _rd.interface().streamRemaining(&_hb.writer) catch |e| @panic(@errorName(e));
    return _hb.written();
}
fn _tcp_close(conn: TcpConn) void { conn.stream.close(); }

const UdpSocket = struct { handle: std.posix.socket_t };
fn _udp_socket() UdpSocket {
    const s = std.posix.socket(std.posix.AF.INET, std.posix.SOCK.DGRAM, 0) catch |e| @panic(@errorName(e));
    return .{ .handle = s };
}
fn _udp_send(sock: UdpSocket, host: []const u8, port: u16, data: []const u8) void {
    const dest = std.net.Address.parseIp4(host, port) catch |e| @panic(@errorName(e));
    _ = std.posix.sendto(sock.handle, data, 0, &dest.any, dest.getOsSockLen()) catch |e| @panic(@errorName(e));
}
fn _udp_recv(sock: UdpSocket, max_bytes: usize) []const u8 {
    const buf = std.heap.page_allocator.alloc(u8, max_bytes) catch @panic("OOM");
    const n = std.posix.recv(sock.handle, buf, 0) catch |e| @panic(@errorName(e));
    return buf[0..n];
}
fn _udp_close(sock: UdpSocket) void { std.posix.close(sock.handle); }

pub const Main = struct {
    pub fn main() void {
        const sock: UdpSocket = _udp_socket();
        _udp_send(sock, "127.0.0.1", 9999, "hello udp");
        _udp_close(sock);
        std.debug.print("{s}\n", .{"ok"});
    }

};

pub fn main() !void {
    defer _ = _gpa.deinit();
    Main.main();
}
